services:
  nachet-db:
    container_name: nachet-db
    image: postgres:15-bookworm
    env_file:
      - ./db/.env.config.local
    ports:
      - "12432:5432"
    volumes:
      - ./db/postgres-data/data:/var/lib/postgresql/data
    # network_mode: bridge
    networks:
      - nachet-local-network

  nachet-pgadmin:
    container_name: nachet-pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - nachet-db
    env_file:
      - ./db/.env.config.local
    volumes: 
      - ./db/pgadmin-data:/var/lib/pgadmin
    ports:
      - '12433:80'
    networks:
      - nachet-local-network

  nachet-blob:
    container_name: nachet-blob
    image: mcr.microsoft.com/azure-storage/azurite:3.35.0
    hostname: azurite
    restart: always
    # command: "azurite --blobHost 127.0.0.1 --blobPort 10000 --queueHost 127.0.0.1 --queuePort 10001"
    command: "azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --location /workspace --debug /workspace/debug.log"
    volumes:
      - ./blob/data:/workspace
    ports:
      - "12434:10000"
    # network_mode: bridge
    networks:
      - nachet-local-network

  nachet-backend:
    container_name: nachet-backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile.local
    image: ghcr.io/ai-cfia/nachet-backend:1.0.4
    # command: ["hypercorn -b :5174 app:app"]
    env_file:
      # - ./nachet-backend/.env.secrets.local
      # - ./nachet-backend/.env.config.local
      - ./backend/.env.local
    ports:
      - "12435:5174"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - nachet-db
      - nachet-blob
    # network_mode: bridge
    networks:
      - nachet-local-network

  nachet-frontend:
    container_name: nachet-frontend
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile.dev
    image: ghcr.io/ai-cfia/nachet-frontend:0.9.31
    # command: ["npm run dev --host"]
    env_file:
      - ./frontend/.env.config.local
    volumes:
      - ./frontend:/app
    ports:
      # - "12436:5173" 
      - "12436:3000" # for ghcr images
    depends_on:
      - nachet-backend

#######################################################################################
# Use these to test with mock model containers
#######################################################################################
  nachet-detector:
    image: wiremock/wiremock:3.13.1
    container_name: nachet-detector
    command: ["--port", "5001", "--verbose"]
    ports:
      - 12380:5001
    volumes:
      - ./e2e/mocks/nachet-detector:/home/wiremock/mappings
    networks:
      - nachet-local-network
  nachet-15spp-classifier:
    image: wiremock/wiremock:3.13.1
    container_name: nachet-15spp-classifier
    command: ["--port", "5001", "--verbose"]
    ports:
      - 12390:5001
    volumes:
      - ./e2e/mocks/nachet-15spp-classifier:/home/wiremock/mappings
    networks:
      - nachet-local-network
  nachet-27spp-classifier:
    image: wiremock/wiremock:3.13.1
    container_name: nachet-27spp-classifier
    command: ["--port", "8080", "--verbose"]
    ports:
      - 12360:8080
    volumes:
      - ./e2e/mocks/nachet-27spp-classifier:/home/wiremock/mappings
    networks:
      - nachet-local-network


#######################################################################################
# Use these to test with actual model containers either prebuilt or as part of monorepo
#######################################################################################
  # nachet-detector:
  #   # build:
  #   #   context: ./nachet-model/AzureMLSeedDet
  #   #   dockerfile: Dockerfile
  #   container_name: nachet-detector
  #   image: ghcr.io/ai-cfia/nachet-backend:29-azureml-seed-detector
  #   command: "./startup.sh && bash -c 'azmlinfsrv --entry_script /app/scoring_file_v_1_0_0.py'"
  #   ports:
  #     - "12380:5001"
  #     - "12381:8883"
  #     - "12382:8888"
  #   # network_mode: bridge
  #   networks:
  #     - nachet-local-network

  # nachet-15spp-classifier:
  #   # build:
  #   #   context: ./nachet-model/AzureMLSeedCls
  #   #   dockerfile: Dockerfile
  #   container_name: nachet-15spp-classifier
  #   image: ghcr.io/ai-cfia/nachet-backend:29-azureml-swin-classifier
  #   command: bash -c 'azmlinfsrv --entry_script /app/score.py'
  #   ports:
  #     - "12390:5001"
  #     - "12391:8883"
  #     - "12392:8888"
  #   # network_mode: bridge
  #   networks:
  #     - nachet-local-network

  # # nachet-22spp-swin:
  # #   # build:
  # #   #   context: ./nachet-model/AzureMLSeedCls_22_spp
  # #   #   dockerfile: Dockerfile
  # #   container_name: nachet-22spp-swin
  # #   image: ghcr.io/ai-cfia/nachet-backend:29-azureml-swin-classifier-22-spp
  # #   command: bash -c 'azmlinfsrv --entry_script /app/score.py'
  # #   ports:
  # #     - "12370:5001"
  # #     - "12371:8883"
  # #     - "12372:8888"
  # #   # network_mode: bridge
  # #   networks:
  # #     - nachet-local-network

  # nachet-27spp-classifier:
  #   # build:
  #   #   context: ./nachet-model/AzureMLSeedCls_27_spp
  #   #   dockerfile: Dockerfile
  #   container_name: nachet-27spp-classifier
  #   image: ghcr.io/ai-cfia/nachet-model-ccds/gpu-classifier-27spp-model-1:2025030321
  #   ports:
  #     - "12360:8080"
  #     # - "12361:8081"
  #     # - "12362:8082"
  #   # network_mode: bridge
  #   networks:
  #     - nachet-local-network

networks:
  nachet-local-network: {}
