services:
  nachet-db:
    container_name: nachet-db
    image: postgres:18-bookworm
    env_file:
      - ./db/.env.config.local
    ports:
      - "12432:5432"
    volumes:
      - ./db/postgres-data/data:/var/lib/postgresql
    # network_mode: bridge
    networks:
      - nachet-local-network

  nachet-pgadmin:
    container_name: nachet-pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - nachet-db
    env_file:
      - ./db/.env.config.local
    volumes:
      - ./db/pgadmin-data/data:/var/lib/pgadmin
    ports:
      - "12433:80"
    networks:
      - nachet-local-network

  nachet-blob:
    container_name: nachet-blob
    image: mcr.microsoft.com/azure-storage/azurite:3.35.0
    hostname: azurite
    restart: always
    # command: "azurite --blobHost 127.0.0.1 --blobPort 10000 --queueHost 127.0.0.1 --queuePort 10001"
    command: "azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --location /workspace --debug /workspace/debug.log"
    volumes:
      - ./blob/azurite/data:/workspace
    ports:
      - "12434:10000"
    # network_mode: bridge
    networks:
      - nachet-local-network

  nachet-backend:
    container_name: nachet-backend

    # uncomment these to build backend from source
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    image: local/nachet-backend:latest

    # uncomment these to use prebuilt image from ghcr
    # image: ghcr.io/ai-cfia/nachet-backend:1.0.4
    command: ["uv", "run", "hypercorn", "-b", ":5174", "app/main:app"]
    env_file:
      # - ./nachet-backend/.env.secrets.local
      # - ./nachet-backend/.env.config.local
      - ./backend/.env.container.local
    ports:
      - "12435:5174"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - nachet-db
      - nachet-blob
    # network_mode: bridge
    networks:
      - nachet-local-network

  # optional frontend service, uncomment to use
  # for debugging dev build
  # nachet-frontend:
  #   container_name: nachet-frontend

  #   # uncomment these to build frontend from source
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   image: local/nachet-frontend:latest

  #   # uncomment these to use prebuilt image from ghcr
  #   # image: ghcr.io/ai-cfia/nachet-frontend:0.10.3
  #   # command: ["npm run dev --host"]
  #   env_file:
  #     - ./frontend/.env.config.local
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     # - "12436:5173"
  #     - "12436:12436" # for ghcr images
  #   depends_on:
  #     - nachet-backend

  #######################################################################################
  # Use these to deploy a second version of backend and frontend for testing
  #######################################################################################

  # nachet-backend-v1:
  #   container_name: nachet-backend-v1
  #   image: ghcr.io/ai-cfia/nachet-backend:265
  #   command: ["uv", "run", "hypercorn", "-b", ":5175", "app:app"]
  #   env_file:
  #     # - ./nachet-backend/.env.secrets.local
  #     # - ./nachet-backend/.env.config.local
  #     - ./backend/.env.bkp.local
  #   ports:
  #     - "12437:5175"
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   depends_on:
  #     - nachet-db
  #     - nachet-blob
  #   # network_mode: bridge
  #   networks:
  #     - nachet-local-network
  #     - nachet-network

  # nachet-frontend-v1:
  #   container_name: nachet-frontend-v1
  #   image: ghcr.io/ai-cfia/nachet-frontend:0.9.31
  #   command: ["npm run dev --host"]
  #   env_file:
  #     - ./frontend/.env.config.local
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     # - "12436:5173"
  #     - "12438:12436" # for ghcr images
  #   depends_on:
  #     - nachet-backend

  #######################################################################################
  # Use these to test with mock model containers
  #######################################################################################
  nachet-detector:
    image: wiremock/wiremock:3.13.2
    container_name: nachet-detector
    command: ["--port", "5001", "--verbose"]
    ports:
      - 12380:5001
    volumes:
      - ./e2e/mocks/nachet-detector:/home/wiremock/mappings
    networks:
      - nachet-local-network
  nachet-15spp-classifier:
    image: wiremock/wiremock:3.13.2
    container_name: nachet-15spp-classifier
    command: ["--port", "5001", "--verbose"]
    ports:
      - 12390:5001
    volumes:
      - ./e2e/mocks/nachet-15spp-classifier:/home/wiremock/mappings
    networks:
      - nachet-local-network
  nachet-27spp-classifier:
    image: wiremock/wiremock:3.13.2
    container_name: nachet-27spp-classifier
    command: ["--port", "8080", "--verbose"]
    ports:
      - 12360:8080
    volumes:
      - ./e2e/mocks/nachet-27spp-classifier:/home/wiremock/mappings
    networks:
      - nachet-local-network

  #######################################################################################
  # Use these to test with actual model containers either prebuilt or as part of monorepo
  #######################################################################################
  # nachet-detector:
  #   # build:
  #   #   context: ./nachet-model/AzureMLSeedDet
  #   #   dockerfile: Dockerfile
  #   container_name: nachet-detector
  #   image: ghcr.io/ai-cfia/nachet-backend:29-azureml-seed-detector
  #   command: "./startup.sh && bash -c 'azmlinfsrv --entry_script /app/scoring_file_v_1_0_0.py'"
  #   ports:
  #     - "12380:5001"
  #     - "12381:8883"
  #     - "12382:8888"
  #   # network_mode: bridge
  #   networks:
  #     - nachet-local-network
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4.0'

  # nachet-15spp-classifier:
  #   # build:
  #   #   context: ./nachet-model/AzureMLSeedCls
  #   #   dockerfile: Dockerfile
  #   container_name: nachet-15spp-classifier
  #   image: ghcr.io/ai-cfia/nachet-backend:29-azureml-swin-classifier
  #   command: bash -c 'azmlinfsrv --entry_script /app/score.py'
  #   ports:
  #     - "12390:5001"
  #     - "12391:8883"
  #     - "12392:8888"
  #   # network_mode: bridge
  #   networks:
  #     - nachet-local-network
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4.0'

  # # nachet-22spp-swin:
  # #   # build:
  # #   #   context: ./nachet-model/AzureMLSeedCls_22_spp
  # #   #   dockerfile: Dockerfile
  # #   container_name: nachet-22spp-swin
  # #   image: ghcr.io/ai-cfia/nachet-backend:29-azureml-swin-classifier-22-spp
  # #   command: bash -c 'azmlinfsrv --entry_script /app/score.py'
  # #   ports:
  # #     - "12370:5001"
  # #     - "12371:8883"
  # #     - "12372:8888"
  # #   # network_mode: bridge
  # #   networks:
  # #     - nachet-local-network

  # nachet-27spp-classifier:
  #   # build:
  #   #   context: ./nachet-model/AzureMLSeedCls_27_spp
  #   #   dockerfile: Dockerfile
  #   container_name: nachet-27spp-classifier
  #   image: ghcr.io/ai-cfia/nachet-model-ccds/gpu-classifier-27spp-model-1:2025030321
  #   ports:
  #     - "12360:8080"
  #     # - "12361:8081"
  #     # - "12362:8082"
  #   # network_mode: bridge
  #   networks:
  #     - nachet-local-network
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4.0'

  #######################################################################################
  # Observability Stack - Grafana Alloy, Loki, Grafana
  #######################################################################################

  loki:
    container_name: nachet-loki
    image: grafana/loki:3.6.2
    ports:
      - "12310:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./observability/loki-data:/loki
    networks:
      - nachet-local-network

  alloy:
    container_name: nachet-alloy
    image: grafana/alloy:v1.11.3
    ports:
      - "12317:4317" # OTLP gRPC receiver
      - "12318:4318" # OTLP HTTP receiver
      - "12345:12345" # Alloy UI
    volumes:
      - ./observability/alloy-config.yaml:/etc/alloy/config.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki
    networks:
      - nachet-local-network

  grafana:
    container_name: nachet-grafana
    image: grafana/grafana:12.3.0
    ports:
      - "12300:3000"
    env_file:
      - ./observability/.env.local
    volumes:
      - ./observability/grafana-data:/var/lib/grafana
      - ./observability/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./observability/grafana-dashboards-provisioning.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./observability/grafana-dashboard-nachet.json:/etc/grafana/provisioning/dashboards/grafana-dashboard-nachet.json
    depends_on:
      - loki
    networks:
      - nachet-local-network

  #######################################################################################
  # S3 compatible storage options
  #######################################################################################

  # Garage S3 compatible storage
  nachet-op-blob:
    image: dxflrs/garage:v2.1.0
    container_name: nachet-op-blob
    restart: unless-stopped
    environment:
      - RUST_LOG=garage=debug
    ports:
      - "12440:12440"
      - "12441:12441"
      # - "12442:12442"
      - "12443:12443"
      # - "12444:12444"
    volumes:
      - ./blob/garage/garage.toml.local:/etc/garage.toml
      - ./blob/garage/meta:/var/lib/garage/meta
      - ./blob/garage/data:/var/lib/garage/data
    networks:
      - nachet-local-network

  nachet-op-blob-webui:
    image: khairul169/garage-webui:latest
    container_name: nachet-op-blob-webui
    restart: unless-stopped
    volumes:
      - ./blob/garage/garage.toml.local:/etc/garage.toml:ro
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://nachet-op-blob:12443"
      S3_ENDPOINT_URL: "http://nachet-op-blob:12440"
    extra_hosts:
     - "host.docker.internal:host-gateway"
    depends_on:
      - nachet-op-blob
    networks:
      - nachet-local-network

  # Optional, garage is less complex
  # Only use this if you need S3 features not available in garage
  # ozone S3 compatible storage containers
  # datanode:
  #   container_name: nachet-oz-datanode
  #   image: ${OZONE_IMAGE:-apache/ozone}:${OZONE_IMAGE_VERSION:-2.0.0}${OZONE_IMAGE_FLAVOR:-}
  #   ports:
  #     - 9864
  #   environment:
  #       OZONE-SITE.XML_hdds.datanode.dir: "blob/ozone/data/hdds"
  #       OZONE-SITE.XML_ozone.metadata.dirs: "blob/ozone/data/metadata"
  #       OZONE-SITE.XML_ozone.om.address: "om"
  #       OZONE-SITE.XML_ozone.om.http-address: "om:9874"
  #       OZONE-SITE.XML_ozone.recon.address: "recon:9891"
  #       OZONE-SITE.XML_ozone.recon.db.dir: "blob/ozone/data/metadata/recon"
  #       OZONE-SITE.XML_ozone.replication: "1"
  #       OZONE-SITE.XML_ozone.scm.block.client.address: "scm"
  #       OZONE-SITE.XML_ozone.scm.client.address: "scm"
  #       OZONE-SITE.XML_ozone.scm.datanode.id.dir: "blob/ozone/data/metadata"
  #       OZONE-SITE.XML_ozone.scm.names: "scm"
  #       no_proxy: "om,recon,scm,s3g,localhost,127.0.0.1"
  #   command: ["ozone", "datanode"]
  #   networks:
  #     - nachet-local-network
  # om:
  #   container_name: nachet-oz-om
  #   image: ${OZONE_IMAGE:-apache/ozone}:${OZONE_IMAGE_VERSION:-2.0.0}${OZONE_IMAGE_FLAVOR:-}
  #   ports:
  #     - 9874:9874
  #   environment:
  #     OZONE-SITE.XML_hdds.datanode.dir: "blob/ozone/data/hdds"
  #     OZONE-SITE.XML_ozone.metadata.dirs: "blob/ozone/data/metadata"
  #     OZONE-SITE.XML_ozone.om.address: "om"
  #     OZONE-SITE.XML_ozone.om.http-address: "om:9874"
  #     OZONE-SITE.XML_ozone.recon.address: "recon:9891"
  #     OZONE-SITE.XML_ozone.recon.db.dir: "blob/ozone/data/metadata/recon"
  #     OZONE-SITE.XML_ozone.replication: "1"
  #     OZONE-SITE.XML_ozone.scm.block.client.address: "scm"
  #     OZONE-SITE.XML_ozone.scm.client.address: "scm"
  #     OZONE-SITE.XML_ozone.scm.datanode.id.dir: "blob/ozone/data/metadata"
  #     OZONE-SITE.XML_ozone.scm.names: "scm"
  #     no_proxy: "om,recon,scm,s3g,localhost,127.0.0.1"
  #     CORE-SITE.XML_hadoop.proxyuser.hadoop.hosts: "*"
  #     CORE-SITE.XML_hadoop.proxyuser.hadoop.groups: "*"
  #     ENSURE_OM_INITIALIZED: /data/metadata/om/current/VERSION
  #     WAITFOR: scm:9876
  #   command: ["ozone", "om"]
  #   networks:
  #     - nachet-local-network
  # scm:
  #   container_name: nachet-oz-scm
  #   image: ${OZONE_IMAGE:-apache/ozone}:${OZONE_IMAGE_VERSION:-2.0.0}${OZONE_IMAGE_FLAVOR:-}
  #   ports:
  #     - 9876:9876
  #   environment:
  #     OZONE-SITE.XML_hdds.datanode.dir: "blob/ozone/data/hdds"
  #     OZONE-SITE.XML_ozone.metadata.dirs: "blob/ozone/data/metadata"
  #     OZONE-SITE.XML_ozone.om.address: "om"
  #     OZONE-SITE.XML_ozone.om.http-address: "om:9874"
  #     OZONE-SITE.XML_ozone.recon.address: "recon:9891"
  #     OZONE-SITE.XML_ozone.recon.db.dir: "blob/ozone/data/metadata/recon"
  #     OZONE-SITE.XML_ozone.replication: "1"
  #     OZONE-SITE.XML_ozone.scm.block.client.address: "scm"
  #     OZONE-SITE.XML_ozone.scm.client.address: "scm"
  #     OZONE-SITE.XML_ozone.scm.datanode.id.dir: "blob/ozone/data/metadata"
  #     OZONE-SITE.XML_ozone.scm.names: "scm"
  #     no_proxy: "om,recon,scm,s3g,localhost,127.0.0.1"
  #     ENSURE_SCM_INITIALIZED: /data/metadata/scm/current/VERSION
  #   command: ["ozone", "scm"]
  #   networks:
  #     - nachet-local-network
  # recon:
  #   container_name: nachet-oz-recon
  #   image: ${OZONE_IMAGE:-apache/ozone}:${OZONE_IMAGE_VERSION:-2.0.0}${OZONE_IMAGE_FLAVOR:-}
  #   ports:
  #     - 9888:9888
  #   environment:
  #     OZONE-SITE.XML_hdds.datanode.dir: "blob/ozone/data/hdds"
  #     OZONE-SITE.XML_ozone.metadata.dirs: "blob/ozone/data/metadata"
  #     OZONE-SITE.XML_ozone.om.address: "om"
  #     OZONE-SITE.XML_ozone.om.http-address: "om:9874"
  #     OZONE-SITE.XML_ozone.recon.address: "recon:9891"
  #     OZONE-SITE.XML_ozone.recon.db.dir: "blob/ozone/data/metadata/recon"
  #     OZONE-SITE.XML_ozone.replication: "1"
  #     OZONE-SITE.XML_ozone.scm.block.client.address: "scm"
  #     OZONE-SITE.XML_ozone.scm.client.address: "scm"
  #     OZONE-SITE.XML_ozone.scm.datanode.id.dir: "blob/ozone/data/metadata"
  #     OZONE-SITE.XML_ozone.scm.names: "scm"
  #     no_proxy: "om,recon,scm,s3g,localhost,127.0.0.1"
  #   command: ["ozone", "recon"]
  #   networks:
  #     - nachet-local-network
  # s3g:
  #   container_name: nachet-oz-s3g
  #   image: ${OZONE_IMAGE:-apache/ozone}:${OZONE_IMAGE_VERSION:-2.0.0}${OZONE_IMAGE_FLAVOR:-}
  #   ports:
  #     - 9878:9878
  #   environment:
  #     OZONE-SITE.XML_hdds.datanode.dir: "blob/ozone/data/hdds"
  #     OZONE-SITE.XML_ozone.metadata.dirs: "blob/ozone/data/metadata"
  #     OZONE-SITE.XML_ozone.om.address: "om"
  #     OZONE-SITE.XML_ozone.om.http-address: "om:9874"
  #     OZONE-SITE.XML_ozone.recon.address: "recon:9891"
  #     OZONE-SITE.XML_ozone.recon.db.dir: "blob/ozone/data/metadata/recon"
  #     OZONE-SITE.XML_ozone.replication: "1"
  #     OZONE-SITE.XML_ozone.scm.block.client.address: "scm"
  #     OZONE-SITE.XML_ozone.scm.client.address: "scm"
  #     OZONE-SITE.XML_ozone.scm.datanode.id.dir: "blob/ozone/data/metadata"
  #     OZONE-SITE.XML_ozone.scm.names: "scm"
  #     no_proxy: "om,recon,scm,s3g,localhost,127.0.0.1"
  #   command: ["ozone", "s3g"]
  #   networks:
  #     - nachet-local-network
  # httpfs:
  #   container_name: nachet-oz-httpfs
  #   image: ${OZONE_IMAGE:-apache/ozone}:${OZONE_IMAGE_VERSION:-2.0.0}${OZONE_IMAGE_FLAVOR:-}
  #   ports:
  #     - 14000:14000
  #   environment:
  #     OZONE-SITE.XML_hdds.datanode.dir: "blob/ozone/data/hdds"
  #     OZONE-SITE.XML_ozone.metadata.dirs: "blob/ozone/data/metadata"
  #     OZONE-SITE.XML_ozone.om.address: "om"
  #     OZONE-SITE.XML_ozone.om.http-address: "om:9874"
  #     OZONE-SITE.XML_ozone.recon.address: "recon:9891"
  #     OZONE-SITE.XML_ozone.recon.db.dir: "blob/ozone/data/metadata/recon"
  #     OZONE-SITE.XML_ozone.replication: "1"
  #     OZONE-SITE.XML_ozone.scm.block.client.address: "scm"
  #     OZONE-SITE.XML_ozone.scm.client.address: "scm"
  #     OZONE-SITE.XML_ozone.scm.datanode.id.dir: "blob/ozone/data/metadata"
  #     OZONE-SITE.XML_ozone.scm.names: "scm"
  #     no_proxy: "om,recon,scm,s3g,localhost,127.0.0.1"
  #     CORE-SITE.XML_fs.defaultFS: "ofs://om"
  #   command: ["ozone", "httpfs"]
  #   networks:
  #     - nachet-local-network

networks:
  nachet-local-network: {}
  nachet-network:
    external: true
