// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CheckIfUserIsRegisteredAuthRequiredIsRegisteredGetData,
  CheckIfUserIsRegisteredAuthRequiredIsRegisteredGetResponses,
  CreateOrGetFolderAuthRequiredFoldersPostData,
  CreateOrGetFolderAuthRequiredFoldersPostErrors,
  CreateOrGetFolderAuthRequiredFoldersPostResponses,
  DeleteFolderAuthRequiredFoldersFolderIdDeleteData,
  DeleteFolderAuthRequiredFoldersFolderIdDeleteErrors,
  DeleteFolderAuthRequiredFoldersFolderIdDeleteResponses,
  FrontendLogEndpointAuthRequiredLogsPostData,
  FrontendLogEndpointAuthRequiredLogsPostErrors,
  FrontendLogEndpointAuthRequiredLogsPostResponses,
  GetAllDevicesAuthRequiredDevicesGetData,
  GetAllDevicesAuthRequiredDevicesGetResponses,
  GetApiVersionNoAuthRequiredVersionGetData,
  GetApiVersionNoAuthRequiredVersionGetResponses,
  GetDirectoriesAuthRequiredGetDirectoriesGetData,
  GetDirectoriesAuthRequiredGetDirectoriesGetResponses,
  GetHealthStatusNoAuthRequiredHealthGetData,
  GetHealthStatusNoAuthRequiredHealthGetResponses,
  GetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetData,
  GetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetResponses,
  GetPipelinesAuthRequiredPipelinesGetData,
  GetPipelinesAuthRequiredPipelinesGetResponses,
  GetReadinessStatusNoAuthRequiredReadyGetData,
  GetReadinessStatusNoAuthRequiredReadyGetResponses,
  GetSeedDataAuthRequiredSeedsGetData,
  GetSeedDataAuthRequiredSeedsGetResponses,
  GetUserIdFromEmailAuthRequiredGetUserIdPostData,
  GetUserIdFromEmailAuthRequiredGetUserIdPostResponses,
  GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetData,
  GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetErrors,
  GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetResponses,
  GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetData,
  GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetErrors,
  GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetResponses,
  InitializeBatchUploadAuthRequiredNewBatchImportPostData,
  InitializeBatchUploadAuthRequiredNewBatchImportPostErrors,
  InitializeBatchUploadAuthRequiredNewBatchImportPostResponses,
  LogoutUserNoAuthRequiredLogoutGetData,
  LogoutUserNoAuthRequiredLogoutGetResponses,
  RateLimitTestNoAuthRequiredRateLimitTestGetData,
  RateLimitTestNoAuthRequiredRateLimitTestGetResponses,
  SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostData,
  SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostErrors,
  SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostResponses,
  SubmitImageForProcessingAuthRequiredInfPostData,
  SubmitImageForProcessingAuthRequiredInfPostErrors,
  SubmitImageForProcessingAuthRequiredInfPostResponses,
  UpdateFolderAuthRequiredFoldersFolderIdPutData,
  UpdateFolderAuthRequiredFoldersFolderIdPutErrors,
  UpdateFolderAuthRequiredFoldersFolderIdPutResponses,
  UploadPictureInBatchAuthRequiredUploadPicturePostData,
  UploadPictureInBatchAuthRequiredUploadPicturePostErrors,
  UploadPictureInBatchAuthRequiredUploadPicturePostResponses,
} from "./types.gen";
import {
  zCheckIfUserIsRegisteredAuthRequiredIsRegisteredGetData,
  zCheckIfUserIsRegisteredAuthRequiredIsRegisteredGetResponse,
  zCreateOrGetFolderAuthRequiredFoldersPostData,
  zCreateOrGetFolderAuthRequiredFoldersPostResponse,
  zDeleteFolderAuthRequiredFoldersFolderIdDeleteData,
  zDeleteFolderAuthRequiredFoldersFolderIdDeleteResponse,
  zFrontendLogEndpointAuthRequiredLogsPostData,
  zFrontendLogEndpointAuthRequiredLogsPostResponse,
  zGetAllDevicesAuthRequiredDevicesGetData,
  zGetAllDevicesAuthRequiredDevicesGetResponse,
  zGetApiVersionNoAuthRequiredVersionGetData,
  zGetApiVersionNoAuthRequiredVersionGetResponse,
  zGetDirectoriesAuthRequiredGetDirectoriesGetData,
  zGetDirectoriesAuthRequiredGetDirectoriesGetResponse,
  zGetHealthStatusNoAuthRequiredHealthGetData,
  zGetHealthStatusNoAuthRequiredHealthGetResponse,
  zGetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetData,
  zGetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetResponse,
  zGetPipelinesAuthRequiredPipelinesGetData,
  zGetPipelinesAuthRequiredPipelinesGetResponse,
  zGetReadinessStatusNoAuthRequiredReadyGetData,
  zGetReadinessStatusNoAuthRequiredReadyGetResponse,
  zGetSeedDataAuthRequiredSeedsGetData,
  zGetSeedDataAuthRequiredSeedsGetResponse,
  zGetUserIdFromEmailAuthRequiredGetUserIdPostData,
  zGetUserIdFromEmailAuthRequiredGetUserIdPostResponse,
  zGetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetData,
  zGetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetResponse,
  zGetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetData,
  zGetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetResponse,
  zInitializeBatchUploadAuthRequiredNewBatchImportPostData,
  zInitializeBatchUploadAuthRequiredNewBatchImportPostResponse,
  zLogoutUserNoAuthRequiredLogoutGetData,
  zRateLimitTestNoAuthRequiredRateLimitTestGetData,
  zRateLimitTestNoAuthRequiredRateLimitTestGetResponse,
  zSubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostData,
  zSubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostResponse,
  zSubmitImageForProcessingAuthRequiredInfPostData,
  zSubmitImageForProcessingAuthRequiredInfPostResponse,
  zUpdateFolderAuthRequiredFoldersFolderIdPutData,
  zUpdateFolderAuthRequiredFoldersFolderIdPutResponse,
  zUploadPictureInBatchAuthRequiredUploadPicturePostData,
  zUploadPictureInBatchAuthRequiredUploadPicturePostResponse,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Submit Image For Processing [Auth Required]
 */
export const submitImageForProcessingAuthRequiredInfPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SubmitImageForProcessingAuthRequiredInfPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    SubmitImageForProcessingAuthRequiredInfPostResponses,
    SubmitImageForProcessingAuthRequiredInfPostErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zSubmitImageForProcessingAuthRequiredInfPostData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zSubmitImageForProcessingAuthRequiredInfPostResponse.parseAsync(
        data,
      );
    },
    url: "/inf",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Submit Image For Direct Processing [Cfia Admin Only]
 *
 * Submit an image for direct processing (synchronous).
 * Does not store anything.
 * Direct to the model endpoint and returns the classification result.
 *
 * Returns ApiInferenceResponse with boxes and classifications.
 *
 * Access: CFIA admin only
 */
export const submitImageForDirectProcessingCfiaAdminOnlyInfDirectPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostResponses,
    SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zSubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zSubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostResponse.parseAsync(
        data,
      );
    },
    url: "/inf-direct",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Workflow Status [Auth Required]
 *
 * Get comprehensive workflow status by workflow ID.
 *
 * Accepts any workflow_id (parent, processing, or inference child)
 * and returns status for all related workflows.
 *
 * Authorization: User must own the workflow OR be a CFIA admin.
 *
 * Returns detailed status information including:
 * - Workflow type (parent/processing/inference)
 * - Associated image ID
 * - Overall status (pending/in_progress/completed/failed)
 * - Parent workflow status and progress
 * - Processing workflow stages and timestamps
 * - Inference workflow status and details
 * - Authorization metadata
 *
 * Use cases:
 * - Frontend receives workflow_id from POST /inf submission
 * - Frontend polls this endpoint to check progress
 * - Can query by any related workflow ID (parent or child)
 *
 * Returns:
 * Dict with comprehensive workflow status across all related workflows
 */
export const getWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetResponses,
    GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetResponse.parseAsync(
        data,
      );
    },
    url: "/workflow/{workflow_id}/status",
    ...options,
  });
};

/**
 * Get Workflow Results [Auth Required]
 *
 * Get inference results for a completed workflow.
 *
 * Returns formatted inference results including bounding boxes, classifications,
 * and model metadata when the workflow has completed successfully.
 *
 * Authorization: User must own the workflow OR be a CFIA admin.
 *
 * Args:
 * workflow_id: Parent workflow ID returned by POST /inf
 *
 * Returns:
 * ApiInferenceResponse with:
 * - filename: Image filename
 * - imageId: Image UUID
 * - inference_id: Annotation UUID (equals workflow_id)
 * - boxes: List of detected objects with classifications
 * - labelOccurrence: Count of each label
 * - totalBoxes: Total number of detected boxes
 * - models: Model metadata used for inference
 *
 * Raises:
 * 404: If workflow not found or results not ready
 * 403: If user not authorized to access workflow
 * 500: If results retrieval fails
 *
 * Use cases:
 * - Frontend polls /workflow/{id}/status until overall_status == "completed"
 * - Frontend then calls this endpoint to get formatted results
 * - Results are stored in Annotation table with id == parent workflow_id
 */
export const getWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetResponses,
    GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetResponse.parseAsync(
        data,
      );
    },
    url: "/workflow/{workflow_id}/results",
    ...options,
  });
};

/**
 * Rate Limit Test [No Auth Required]
 */
export const rateLimitTestNoAuthRequiredRateLimitTestGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    RateLimitTestNoAuthRequiredRateLimitTestGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    RateLimitTestNoAuthRequiredRateLimitTestGetResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zRateLimitTestNoAuthRequiredRateLimitTestGetData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zRateLimitTestNoAuthRequiredRateLimitTestGetResponse.parseAsync(
        data,
      );
    },
    url: "/rate-limit-test",
    ...options,
  });
};

/**
 * Get Health Status [No Auth Required]
 */
export const getHealthStatusNoAuthRequiredHealthGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetHealthStatusNoAuthRequiredHealthGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetHealthStatusNoAuthRequiredHealthGetResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGetHealthStatusNoAuthRequiredHealthGetData.parseAsync(data);
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetHealthStatusNoAuthRequiredHealthGetResponse.parseAsync(
        data,
      );
    },
    url: "/health",
    ...options,
  });
};

/**
 * Get Api Version [No Auth Required]
 */
export const getApiVersionNoAuthRequiredVersionGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetApiVersionNoAuthRequiredVersionGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiVersionNoAuthRequiredVersionGetResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGetApiVersionNoAuthRequiredVersionGetData.parseAsync(data);
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetApiVersionNoAuthRequiredVersionGetResponse.parseAsync(
        data,
      );
    },
    url: "/version",
    ...options,
  });
};

/**
 * Get Readiness Status [No Auth Required]
 */
export const getReadinessStatusNoAuthRequiredReadyGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetReadinessStatusNoAuthRequiredReadyGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetReadinessStatusNoAuthRequiredReadyGetResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGetReadinessStatusNoAuthRequiredReadyGetData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetReadinessStatusNoAuthRequiredReadyGetResponse.parseAsync(
        data,
      );
    },
    url: "/ready",
    ...options,
  });
};

/**
 * Get User Id From Email [Auth Required]
 */
export const getUserIdFromEmailAuthRequiredGetUserIdPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetUserIdFromEmailAuthRequiredGetUserIdPostData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    GetUserIdFromEmailAuthRequiredGetUserIdPostResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGetUserIdFromEmailAuthRequiredGetUserIdPostData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetUserIdFromEmailAuthRequiredGetUserIdPostResponse.parseAsync(
        data,
      );
    },
    url: "/get-user-id",
    ...options,
  });
};

/**
 * Get Pipelines [Auth Required]
 */
export const getPipelinesAuthRequiredPipelinesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetPipelinesAuthRequiredPipelinesGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetPipelinesAuthRequiredPipelinesGetResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGetPipelinesAuthRequiredPipelinesGetData.parseAsync(data);
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetPipelinesAuthRequiredPipelinesGetResponse.parseAsync(
        data,
      );
    },
    url: "/pipelines",
    ...options,
  });
};

/**
 * Get Model Endpoints Metadata [Auth Required]
 */
export const getModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    GetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetResponse.parseAsync(
        data,
      );
    },
    url: "/model-endpoints-metadata",
    ...options,
  });
};

/**
 * Get Seed Data [Auth Required]
 */
export const getSeedDataAuthRequiredSeedsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetSeedDataAuthRequiredSeedsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetSeedDataAuthRequiredSeedsGetResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGetSeedDataAuthRequiredSeedsGetData.parseAsync(data);
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetSeedDataAuthRequiredSeedsGetResponse.parseAsync(data);
    },
    url: "/seeds",
    ...options,
  });
};

/**
 * Get All Devices [Auth Required]
 */
export const getAllDevicesAuthRequiredDevicesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetAllDevicesAuthRequiredDevicesGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAllDevicesAuthRequiredDevicesGetResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGetAllDevicesAuthRequiredDevicesGetData.parseAsync(data);
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetAllDevicesAuthRequiredDevicesGetResponse.parseAsync(
        data,
      );
    },
    url: "/devices",
    ...options,
  });
};

/**
 * Get Directories [Auth Required]
 */
export const getDirectoriesAuthRequiredGetDirectoriesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetDirectoriesAuthRequiredGetDirectoriesGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    GetDirectoriesAuthRequiredGetDirectoriesGetResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGetDirectoriesAuthRequiredGetDirectoriesGetData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetDirectoriesAuthRequiredGetDirectoriesGetResponse.parseAsync(
        data,
      );
    },
    url: "/get-directories",
    ...options,
  });
};

/**
 * Create Or Get Folder [Auth Required]
 *
 * Get or create a folder using the get-or-create pattern (idempotent).
 *
 * This endpoint checks if a folder exists at the given normalized_path.
 * If it exists, returns the existing folder_id. If not, creates a new folder
 * and returns the new folder_id.
 *
 * Authorization: Any user belonging to an organization
 *
 * Request:
 * normalized_path: Relative path (e.g., "avena-fatua" or "mycology/avena-fatua")
 * description: Optional description for the folder (defaults to empty string)
 *
 * Response:
 * folder_id: UUID of the existing or newly created folder
 */
export const createOrGetFolderAuthRequiredFoldersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateOrGetFolderAuthRequiredFoldersPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateOrGetFolderAuthRequiredFoldersPostResponses,
    CreateOrGetFolderAuthRequiredFoldersPostErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zCreateOrGetFolderAuthRequiredFoldersPostData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zCreateOrGetFolderAuthRequiredFoldersPostResponse.parseAsync(
        data,
      );
    },
    url: "/folders",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Folder [Auth Required]
 *
 * Delete (soft delete) a folder.
 *
 * Authorization: Folder creator (user_id matches) OR org admin OR CFIA admin
 * Restrictions: Cannot delete default folders for active users
 *
 * Response:
 * id: UUID of the deleted folder
 * message: Success message
 *
 * Raises:
 * 403: If user lacks permission or folder is a default folder for active user
 * 404: If folder not found
 */
export const deleteFolderAuthRequiredFoldersFolderIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteFolderAuthRequiredFoldersFolderIdDeleteData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).delete<
    DeleteFolderAuthRequiredFoldersFolderIdDeleteResponses,
    DeleteFolderAuthRequiredFoldersFolderIdDeleteErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zDeleteFolderAuthRequiredFoldersFolderIdDeleteData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zDeleteFolderAuthRequiredFoldersFolderIdDeleteResponse.parseAsync(
        data,
      );
    },
    url: "/folders/{folder_id}",
    ...options,
  });
};

/**
 * Update Folder [Auth Required]
 *
 * Update a folder's name and/or description.
 *
 * Authorization: Users with folder's org_user_role_id OR org_admin_role_id OR CFIA admin
 * Restrictions: Cannot update default folders for active users
 *
 * Request:
 * name: Optional new folder name (just the name, not the full path)
 * description: Optional new description
 *
 * Response:
 * id: UUID of the updated folder
 * message: Success message
 *
 * Raises:
 * 400: If no fields provided or name conflicts with existing folder
 * 403: If user lacks permission or folder is a default folder
 * 404: If folder not found
 */
export const updateFolderAuthRequiredFoldersFolderIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateFolderAuthRequiredFoldersFolderIdPutData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).put<
    UpdateFolderAuthRequiredFoldersFolderIdPutResponses,
    UpdateFolderAuthRequiredFoldersFolderIdPutErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zUpdateFolderAuthRequiredFoldersFolderIdPutData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zUpdateFolderAuthRequiredFoldersFolderIdPutResponse.parseAsync(
        data,
      );
    },
    url: "/folders/{folder_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Check If User Is Registered [Auth Required]
 */
export const checkIfUserIsRegisteredAuthRequiredIsRegisteredGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    CheckIfUserIsRegisteredAuthRequiredIsRegisteredGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    CheckIfUserIsRegisteredAuthRequiredIsRegisteredGetResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zCheckIfUserIsRegisteredAuthRequiredIsRegisteredGetData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zCheckIfUserIsRegisteredAuthRequiredIsRegisteredGetResponse.parseAsync(
        data,
      );
    },
    url: "/is-registered",
    ...options,
  });
};

/**
 * Logout User [No Auth Required]
 */
export const logoutUserNoAuthRequiredLogoutGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<LogoutUserNoAuthRequiredLogoutGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    LogoutUserNoAuthRequiredLogoutGetResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zLogoutUserNoAuthRequiredLogoutGetData.parseAsync(data);
    },
    responseType: "json",
    url: "/logout",
    ...options,
  });
};

/**
 * Frontend Log Endpoint [Auth Required]
 *
 * Accept frontend log messages for centralized logging.
 *
 * Now uses FrontendLogRequest Pydantic model for validation:
 * - Enforces max lengths on all fields
 * - Removes control characters
 * - Validates log level enum
 */
export const frontendLogEndpointAuthRequiredLogsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FrontendLogEndpointAuthRequiredLogsPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    FrontendLogEndpointAuthRequiredLogsPostResponses,
    FrontendLogEndpointAuthRequiredLogsPostErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zFrontendLogEndpointAuthRequiredLogsPostData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zFrontendLogEndpointAuthRequiredLogsPostResponse.parseAsync(
        data,
      );
    },
    url: "/logs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Initialize Batch Upload [Auth Required]
 *
 * Initialize batch upload session.
 *
 * Creates a database-backed session for batch uploading images to an existing folder.
 * Sessions expire after 24 hours and support up to 1000 files.
 *
 * Security:
 * - Requires authentication (Bearer token)
 * - Rate limited to 10 requests/minute
 * - Validates folder exists and belongs to user
 *
 * Request:
 * - folder_id: UUID of existing folder (MUST exist before batch upload)
 * - file_count: Number of images to upload (max 1000)
 *
 * Response:
 * - session_id: UUID for subsequent uploads (valid for 24 hours)
 *
 * Workflow:
 * 1. Validate user has org roles
 * 2. Validate folder exists and belongs to user
 * 3. Validate file_count <= 1000
 * 4. Create database session with 24-hour TTL
 * 5. Return session_id
 *
 * Constraints:
 * - Maximum 1000 files per session
 * - Session expires after 24 hours
 * - Folder must exist before session creation
 * - Folder must belong to authenticated user
 */
export const initializeBatchUploadAuthRequiredNewBatchImportPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    InitializeBatchUploadAuthRequiredNewBatchImportPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    InitializeBatchUploadAuthRequiredNewBatchImportPostResponses,
    InitializeBatchUploadAuthRequiredNewBatchImportPostErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zInitializeBatchUploadAuthRequiredNewBatchImportPostData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zInitializeBatchUploadAuthRequiredNewBatchImportPostResponse.parseAsync(
        data,
      );
    },
    url: "/new-batch-import",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Upload Picture In Batch [Auth Required]
 *
 * Upload single picture in batch - ASYNC WORKFLOW with duplicate detection.
 *
 * Returns immediately with workflow_id. Frontend must poll
 * GET /workflow/{workflow_id}/status for completion.
 *
 * Workflow steps (background):
 * 1. Upload to EXTERNAL storage (nachet-original)
 * 2. Azure Defender malware scan
 * 3. Sanitization function
 * 4. Store in INTERNAL storage (nachet-sanitized)
 *
 * Security:
 * - Requires authentication (Bearer token)
 * - Rate limited to 60 requests/minute
 * - Validates session ownership, expiration, and active status
 * - Validates seed exists
 * - Reuses existing DBOS workflow (Defender + sanitization)
 *
 * Request:
 * - session_id: From /new-batch-import (must be active and not expired)
 * - seed_id: UUID of existing seed record (validated before upload)
 * - tray_code: Sample tray identifier (A-E)
 * - sample_id: Becomes picture.name field
 * - device_*_id, magnification: Device metadata
 * - image: Base64 data URL
 *
 * Response (Success):
 * - workflow_id: Poll /workflow/{id}/status
 * - picture_id: Image UUID
 *
 * Response (Duplicate):
 * - 400 BAD_REQUEST with existing picture_id
 * - Both uploaded_count and duplicate_count incremented
 * - No workflow enqueued
 *
 * Response (Session Expired):
 * - 400 BAD_REQUEST "Session expired (24-hour limit exceeded)"
 *
 * Response (Invalid Seed):
 * - 400 BAD_REQUEST "Seed not found: {seed_id}"
 *
 * Duplicate Handling:
 * - Detects duplicates via SHA256 hash collision
 * - Increments session uploaded_count and duplicate_count
 * - Returns error with existing picture_id
 * - Does NOT create new picture or enqueue workflow
 *
 * Session Completion:
 * - When uploaded_count >= file_count, session marked inactive
 * - Both successful uploads and duplicates count toward file_count
 *
 * Note: FRONTEND MODIFICATION REQUIRED for async polling.
 * See BATCH_UPLOAD_IMPLEMENTATION_PLAN.md for details.
 */
export const uploadPictureInBatchAuthRequiredUploadPicturePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UploadPictureInBatchAuthRequiredUploadPicturePostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    UploadPictureInBatchAuthRequiredUploadPicturePostResponses,
    UploadPictureInBatchAuthRequiredUploadPicturePostErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zUploadPictureInBatchAuthRequiredUploadPicturePostData.parseAsync(
        data,
      );
    },
    responseType: "json",
    responseValidator: async (data) => {
      return await zUploadPictureInBatchAuthRequiredUploadPicturePostResponse.parseAsync(
        data,
      );
    },
    url: "/upload-picture",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
