// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

/**
 * ApiInferenceBox
 *
 * Inference box matching frontend InferenceBoxApiSchema.
 *
 * This is the exact format expected by the frontend for each box in the inference results.
 * Includes all required fields for frontend visualization and interaction.
 *
 * Note: Frontend expects PIXEL coordinates, not normalized coordinates!
 */
export type ApiInferenceBox = {
  box: PixelBoundingBox;
  /**
   * Label
   *
   * Primary classification label
   */
  label: string;
  /**
   * Score
   *
   * Confidence score
   */
  score: number;
  /**
   * Topn
   *
   * Top-N predictions
   */
  topN: Array<TopNPredictionCleaned>;
  /**
   * Classid
   *
   * Unique identifier for this classification
   */
  classId: string;
  /**
   * Object Type Id
   *
   * Type identifier for the detected object
   */
  object_type_id: string;
  /**
   * Box Id
   *
   * Unique identifier for this bounding box
   */
  box_id: string;
  /**
   * Overlapping
   *
   * Whether this box overlaps with others
   */
  overlapping: boolean;
  /**
   * Overlappingindices
   *
   * Index of overlapping box (if any), -1 if none
   */
  overlappingIndices: number;
  /**
   * Is Verified
   *
   * Whether this box has been verified by user
   */
  is_verified?: boolean;
};

/**
 * ApiInferenceResponse
 *
 * Complete inference response matching frontend ApiInferenceDataSchema.
 *
 * This is the format expected by the frontend for inference results.
 * Used by /inf-direct endpoint.
 */
export type ApiInferenceResponse = {
  /**
   * Filename
   */
  filename: string;
  /**
   * Imageid
   *
   * Image UUID or identifier
   */
  imageId: string;
  /**
   * Inferenceid
   *
   * Inference UUID or identifier
   */
  inferenceId: string;
  /**
   * Boxes
   */
  boxes: Array<ApiInferenceBox>;
  /**
   * Labeloccurrence
   *
   * Count of each label found in the image
   */
  labelOccurrence: {
    [key: string]: number;
  };
  /**
   * Totalboxes
   *
   * Total number of detected boxes
   */
  totalBoxes: number;
  /**
   * Models
   *
   * Models used for inference
   */
  models: Array<ModelInfo>;
};

/**
 * BatchUploadImageRequest
 *
 * Upload single image in batch.
 *
 * This request is submitted for each image in the batch session.
 * The image goes through the full security pipeline (Defender scan + sanitization).
 * Duplicate images (same SHA256 hash) are tracked but not saved.
 */
export type BatchUploadImageRequest = {
  /**
   * Sessionid
   *
   * Session UUID from /new-batch-import
   */
  sessionId: string;
  /**
   * Seedid
   *
   * UUID of existing seed record
   */
  seedId: string;
  /**
   * Traycode
   */
  trayCode: "A" | "B" | "C" | "D" | "E";
  /**
   * Sampleid
   *
   * Becomes picture.name
   */
  sampleId: string;
  /**
   * Imagedescription
   *
   * Description for the image
   */
  imageDescription: string;
  /**
   * Devicebrandid
   */
  deviceBrandId: string;
  /**
   * Devicemodelid
   */
  deviceModelId: string;
  /**
   * Devicelensid
   */
  deviceLensId: string;
  /**
   * Magnification
   */
  magnification: number;
  /**
   * Image
   *
   * Base64 data URL
   */
  image: string;
};

/**
 * BatchUploadImageResponse
 *
 * Response from image upload - ASYNC WORKFLOW PATTERN.
 *
 * The image is queued for processing in the background.
 * Frontend must poll GET /workflow/{workflow_id}/status for completion.
 */
export type BatchUploadImageResponse = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Pictureid
   */
  pictureId?: string | null;
  /**
   * Workflowid
   *
   * For status polling
   */
  workflowId?: string | null;
  /**
   * Error
   */
  error?: string | null;
};

/**
 * BatchUploadInitRequest
 *
 * Initialize batch upload session.
 *
 * The folder must exist before batch upload starts.
 * Returns a session_id for subsequent upload requests.
 * Sessions expire after 24 hours and support up to 1000 files.
 */
export type BatchUploadInitRequest = {
  /**
   * Folderid
   *
   * UUID of existing folder
   */
  folderId: string;
  /**
   * Filecount
   *
   * Number of files to upload (max 1000)
   */
  fileCount: number;
};

/**
 * BatchUploadInitResponse
 *
 * Response from batch initialization.
 *
 * Session expires after 24 hours and accepts up to file_count uploads.
 */
export type BatchUploadInitResponse = {
  /**
   * Sessionid
   *
   * UUID of created session
   */
  sessionId: string;
};

/**
 * BlobUrls
 *
 * Blob storage URLs for original and sanitized images.
 */
export type BlobUrls = {
  /**
   * Original
   */
  original?: string | null;
  /**
   * Sanitized
   */
  sanitized?: string | null;
};

/**
 * CreateFolderResponse
 *
 * Response model for folder creation (get-or-create pattern).
 */
export type CreateFolderResponse = {
  /**
   * Folderid
   *
   * UUID of existing or newly created folder
   */
  folderId: string;
};

/**
 * CreateOrGetFolderRequest
 *
 * Request model for creating or retrieving a folder.
 *
 * The normalized_path is a relative path (e.g., 'avena-fatua' or 'mycology/avena-fatua').
 * The backend will prepend the user's organization prefix automatically.
 *
 * Validation is performed in the service layer via DirectoryService._validate_and_parse_fullpath().
 *
 * The description field is optional and defaults to empty string if not provided.
 */
export type CreateOrGetFolderRequest = {
  /**
   * Normalizedpath
   */
  normalizedPath: string;
  /**
   * Description
   */
  description?: string;
};

/**
 * DeleteFolderResponse
 *
 * Response model for folder deletion (soft delete).
 */
export type DeleteFolderResponse = {
  /**
   * Id
   *
   * UUID of the deleted folder
   */
  id: string;
  /**
   * Message
   *
   * Success message
   */
  message: string;
};

/**
 * DevicesResponse
 *
 * Response model for GET /devices endpoint.
 *
 * Returns device information (brands, models, lenses) for image metadata.
 * Uses RootModel since the response is a direct dict structure.
 */
export type DevicesResponse = {
  [key: string]: unknown;
};

/**
 * DirectoriesResponse
 *
 * Response model for GET /get-directories endpoint.
 *
 * Returns user's directory/folder tree structure.
 * Uses RootModel since the response is a direct dict structure.
 */
export type DirectoriesResponse = {
  [key: string]: unknown;
};

/**
 * FrontendLogRequest
 *
 * Request model for frontend log submission.
 *
 * Frontend sends error logs to backend for centralized logging.
 * All fields are validated to prevent abuse (e.g., extremely long strings).
 */
export type FrontendLogRequest = {
  /**
   * Level
   *
   * Log level
   */
  level?: "ERROR" | "WARNING" | "INFO";
  /**
   * Message
   *
   * Log message
   */
  message: string;
  /**
   * Errortype
   *
   * Error type or name
   */
  errorType?: string | null;
  /**
   * Stacktrace
   *
   * Stack trace for errors
   */
  stackTrace?: string | null;
  /**
   * Url
   *
   * URL where error occurred
   */
  url?: string | null;
  /**
   * Correlationid
   *
   * Correlation ID for request tracing
   */
  correlationId?: string | null;
  /**
   * Sessionid
   *
   * Frontend session ID
   */
  sessionId?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Response model for GET /health and GET /ready endpoints.
 *
 * Simple health check response indicating the service is operational.
 */
export type HealthResponse = {
  /**
   * Status
   *
   * Health status (e.g., 'ok', 'ready')
   */
  status: string;
};

/**
 * ImageSubmissionResponse
 *
 * Response model for image submission to processing pipeline.
 */
export type ImageSubmissionResponse = {
  /**
   * Imageid
   */
  imageId: string;
  /**
   * Workflowid
   */
  workflowId: string;
  /**
   * Status
   */
  status: string;
  /**
   * Message
   */
  message: string;
};

/**
 * InferenceRequest
 *
 * Request model for POST /inf endpoint.
 *
 * Matches legacy API format for backwards compatibility.
 * Includes required image metadata fields sent by frontend.
 */
export type InferenceRequest = {
  /**
   * Pipelineid
   */
  pipelineId: string;
  /**
   * Foldername
   */
  folderName: string;
  /**
   * Folderid
   */
  folderId: string;
  /**
   * Imagedims
   *
   * Image dimensions as [width, height]
   */
  imageDims: [number, number];
  /**
   * Image
   */
  image: string;
  /**
   * Arearatio
   */
  areaRatio?: number;
  /**
   * Colorformat
   */
  colorFormat?: string;
  /**
   * Imagename
   *
   * Human-readable name for the image
   */
  imageName: string;
  /**
   * Imagedescription
   *
   * Description or notes about the image
   */
  imageDescription: string;
  /**
   * Devicemodelid
   *
   * UUID of the device model used to capture the image
   */
  deviceModelId: string;
  /**
   * Devicelensid
   *
   * UUID of the lens used to capture the image
   */
  deviceLensId: string;
  /**
   * Sample tray identification code (A-E only)
   */
  trayCode: TrayCode;
  /**
   * Magnification
   *
   * Magnification level used when capturing the image
   */
  magnification: number;
};

/**
 * InferenceWorkflowStatus
 *
 * Status information for ML inference workflow.
 */
export type InferenceWorkflowStatus = {
  /**
   * Workflowid
   */
  workflowId: string;
  /**
   * Status
   */
  status: string;
  /**
   * Pipelineid
   */
  pipelineId: string;
  /**
   * Createdat
   */
  createdAt?: string | null;
  /**
   * Startedat
   */
  startedAt?: string | null;
  /**
   * Completedat
   */
  completedAt?: string | null;
  /**
   * Failedat
   */
  failedAt?: string | null;
  /**
   * Errormessage
   */
  errorMessage?: string | null;
  /**
   * Requestpayload
   */
  requestPayload?: {
    [key: string]: unknown;
  } | null;
};

/**
 * LogSubmissionResponse
 *
 * Response model for frontend log submission.
 *
 * Confirms that the log was received and processed.
 */
export type LogSubmissionResponse = {
  /**
   * Status
   *
   * Processing status (e.g., 'success', 'logged')
   */
  status: string;
  /**
   * Message
   *
   * Optional response message
   */
  message?: string | null;
};

/**
 * ModelEndpointsMetadataResponse
 *
 * Response model for GET /model-endpoints-metadata endpoint.
 *
 * Returns ML model endpoint configuration metadata.
 * Uses RootModel since the response is a direct dict structure.
 */
export type ModelEndpointsMetadataResponse = {
  [key: string]: unknown;
};

/**
 * ModelInfo
 *
 * Model information for API response.
 */
export type ModelInfo = {
  /**
   * Name
   */
  name: string;
  /**
   * Version
   */
  version: string;
};

/**
 * ParentWorkflowStatus
 *
 * Status information for parent (orchestrator) workflow.
 */
export type ParentWorkflowStatus = {
  /**
   * Workflowid
   */
  workflowId: string;
  /**
   * Status
   */
  status: string;
  /**
   * Progresspercentage
   */
  progressPercentage?: number | null;
  /**
   * Createdat
   */
  createdAt?: string | null;
  /**
   * Completedat
   */
  completedAt?: string | null;
  /**
   * Failedat
   */
  failedAt?: string | null;
  /**
   * Errormessage
   */
  errorMessage?: string | null;
  /**
   * Malwaredetected
   */
  malwareDetected?: boolean | null;
};

/**
 * PipelinesResponse
 *
 * Response model for GET /pipelines endpoint.
 *
 * Returns available ML pipelines for seed classification.
 */
export type PipelinesResponse = {
  /**
   * Pipelines
   *
   * List of available pipeline configurations
   */
  pipelines: Array<{
    [key: string]: unknown;
  }>;
};

/**
 * PixelBoundingBox
 *
 * Bounding box coordinates in pixel values.
 *
 * Used after converting from normalized coordinates (0.0-1.0)
 * to absolute pixel positions.
 */
export type PixelBoundingBox = {
  /**
   * Topx
   *
   * Top-left X coordinate (pixels)
   */
  topX: number;
  /**
   * Topy
   *
   * Top-left Y coordinate (pixels)
   */
  topY: number;
  /**
   * Bottomx
   *
   * Bottom-right X coordinate (pixels)
   */
  bottomX: number;
  /**
   * Bottomy
   *
   * Bottom-right Y coordinate (pixels)
   */
  bottomY: number;
};

/**
 * ProcessingStages
 *
 * Processing pipeline stages completion status.
 */
export type ProcessingStages = {
  /**
   * Uploaded
   */
  uploaded: boolean;
  /**
   * Defenderscanning
   */
  defenderScanning: boolean;
  /**
   * Defenderscanned
   */
  defenderScanned: boolean;
  /**
   * Sanitizing
   */
  sanitizing: boolean;
  /**
   * Sanitized
   */
  sanitized: boolean;
};

/**
 * ProcessingTimestamps
 *
 * Timestamps for each processing stage.
 */
export type ProcessingTimestamps = {
  /**
   * Uploadedat
   */
  uploadedAt?: string | null;
  /**
   * Defenderscanstartedat
   */
  defenderScanStartedAt?: string | null;
  /**
   * Defenderscancompletedat
   */
  defenderScanCompletedAt?: string | null;
  /**
   * Sanitizationstartedat
   */
  sanitizationStartedAt?: string | null;
  /**
   * Sanitizationcompletedat
   */
  sanitizationCompletedAt?: string | null;
  /**
   * Completedat
   */
  completedAt?: string | null;
  /**
   * Failedat
   */
  failedAt?: string | null;
};

/**
 * ProcessingWorkflowStatus
 *
 * Detailed status for image processing workflow.
 */
export type ProcessingWorkflowStatus = {
  /**
   * Status
   */
  status: string;
  stages: ProcessingStages;
  timestamps: ProcessingTimestamps;
  /**
   * Defenderscanresult
   */
  defenderScanResult?: string | null;
  blobUrls: BlobUrls;
  /**
   * Errormessage
   */
  errorMessage?: string | null;
  /**
   * Errordetails
   */
  errorDetails?: string | null;
};

/**
 * RateLimitTestResponse
 *
 * Response model for GET /rate-limit-test endpoint.
 *
 * Tests rate limiting functionality.
 */
export type RateLimitTestResponse = {
  /**
   * Message
   *
   * Response message
   */
  message: string;
};

/**
 * RegistrationStatusResponse
 *
 * Response model for GET /is-registered endpoint.
 *
 * Checks if the user is registered in the system.
 */
export type RegistrationStatusResponse = {
  /**
   * Isregistered
   *
   * Whether the user is registered in the system
   */
  isRegistered: boolean;
};

/**
 * SeedDataResponse
 *
 * Response model for GET /seeds endpoint.
 *
 * Returns seed species data for frontend selection.
 * Uses RootModel since the response is a direct dict structure.
 */
export type SeedDataResponse = {
  [key: string]: unknown;
};

/**
 * TopNPredictionCleaned
 *
 * Top-N prediction with cleaned label (index prefix removed).
 */
export type TopNPredictionCleaned = {
  /**
   * Label
   *
   * Classification label without index prefix
   */
  label: string;
  /**
   * Score
   *
   * Confidence score
   */
  score: number;
};

/**
 * TrayCode
 *
 * Valid tray codes for sample identification.
 */
export const TrayCode = {
  A: "A",
  B: "B",
  C: "C",
  D: "D",
  E: "E",
} as const;

/**
 * TrayCode
 *
 * Valid tray codes for sample identification.
 */
// eslint-disable-next-line no-redeclare -- TypeScript allows same name for const and type
export type TrayCode = (typeof TrayCode)[keyof typeof TrayCode];

/**
 * UpdateFolderRequest
 *
 * Request model for updating a folder's name and/or description.
 *
 * Both fields are optional - update only the fields provided.
 * Name validation is performed in the service layer.
 * Description is sanitized on the client side.
 */
export type UpdateFolderRequest = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * UpdateFolderResponse
 *
 * Response model for folder update operations.
 */
export type UpdateFolderResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Message
   */
  message: string;
};

/**
 * UserIdResponse
 *
 * Response model for POST /get-user-id endpoint.
 *
 * Returns the authenticated user's ID.
 */
export type UserIdResponse = {
  /**
   * Userid
   *
   * User's unique identifier (OID from Azure AD)
   */
  userId: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * VersionResponse
 *
 * Response model for GET /version endpoint.
 *
 * Returns the current API version.
 */
export type VersionResponse = {
  /**
   * Version
   *
   * API version string
   */
  version: string;
};

/**
 * WorkflowAuthorization
 *
 * Authorization metadata for workflow access.
 */
export type WorkflowAuthorization = {
  /**
   * Userid
   */
  userId: string;
  /**
   * Isowner
   */
  isOwner: boolean;
  /**
   * Iscfiaadmin
   */
  isCfiaAdmin: boolean;
};

/**
 * WorkflowStatusResponse
 *
 * Comprehensive workflow status response.
 *
 * Returned by GET /workflow/{workflow_id}/status endpoint.
 * Provides complete status tracking for image processing and inference workflows.
 *
 * The response includes:
 * - Overall workflow status and type
 * - Parent workflow orchestration status
 * - Image processing pipeline details and timestamps
 * - ML inference workflow status
 * - Authorization metadata
 */
export type WorkflowStatusResponse = {
  /**
   * Workflowid
   *
   * The queried workflow ID
   */
  workflowId: string;
  /**
   * Workflowtype
   *
   * Workflow type: 'parent', 'processing', or 'inference'
   */
  workflowType: string;
  /**
   * Imageid
   *
   * Associated picture UUID
   */
  imageId: string;
  /**
   * Overallstatus
   *
   * High-level status: 'pending', 'in_progress', 'completed', 'failed'
   */
  overallStatus: string;
  /**
   * Authorization metadata
   */
  authorization: WorkflowAuthorization;
  /**
   * Parent workflow status (if exists)
   */
  parentWorkflow?: ParentWorkflowStatus | null;
  /**
   * Processing workflow details (if exists)
   */
  processingWorkflow?: ProcessingWorkflowStatus | null;
  /**
   * Inference workflow details (if exists)
   */
  inferenceWorkflow?: InferenceWorkflowStatus | null;
  /**
   * Errormessage
   *
   * Error message (if failed)
   */
  errorMessage?: string | null;
  /**
   * Errordetails
   *
   * Detailed error info (if failed)
   */
  errorDetails?: string | null;
};

export type SubmitImageForProcessingAuthRequiredInfPostData = {
  body: InferenceRequest;
  path?: never;
  query?: never;
  url: "/inf";
};

export type SubmitImageForProcessingAuthRequiredInfPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SubmitImageForProcessingAuthRequiredInfPostError =
  SubmitImageForProcessingAuthRequiredInfPostErrors[keyof SubmitImageForProcessingAuthRequiredInfPostErrors];

export type SubmitImageForProcessingAuthRequiredInfPostResponses = {
  /**
   * Successful Response
   */
  200: ImageSubmissionResponse;
};

export type SubmitImageForProcessingAuthRequiredInfPostResponse =
  SubmitImageForProcessingAuthRequiredInfPostResponses[keyof SubmitImageForProcessingAuthRequiredInfPostResponses];

export type SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostData = {
  body: InferenceRequest;
  path?: never;
  query?: never;
  url: "/inf-direct";
};

export type SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostError =
  SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostErrors[keyof SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostErrors];

export type SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostResponses =
  {
    /**
     * Successful Response
     */
    200: ApiInferenceResponse;
  };

export type SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostResponse =
  SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostResponses[keyof SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostResponses];

export type GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetData = {
  body?: never;
  path: {
    /**
     * Workflow Id
     */
    workflow_id: string;
  };
  query?: never;
  url: "/workflow/{workflow_id}/status";
};

export type GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetError =
  GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetErrors[keyof GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetErrors];

export type GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetResponses =
  {
    /**
     * Successful Response
     */
    200: WorkflowStatusResponse;
  };

export type GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetResponse =
  GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetResponses[keyof GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetResponses];

export type GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetData = {
  body?: never;
  path: {
    /**
     * Workflow Id
     */
    workflow_id: string;
  };
  query?: never;
  url: "/workflow/{workflow_id}/results";
};

export type GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetError =
  GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetErrors[keyof GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetErrors];

export type GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetResponses =
  {
    /**
     * Successful Response
     */
    200: ApiInferenceResponse;
  };

export type GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetResponse =
  GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetResponses[keyof GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetResponses];

export type RateLimitTestNoAuthRequiredRateLimitTestGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/rate-limit-test";
};

export type RateLimitTestNoAuthRequiredRateLimitTestGetResponses = {
  /**
   * Successful Response
   */
  200: RateLimitTestResponse;
};

export type RateLimitTestNoAuthRequiredRateLimitTestGetResponse =
  RateLimitTestNoAuthRequiredRateLimitTestGetResponses[keyof RateLimitTestNoAuthRequiredRateLimitTestGetResponses];

export type GetHealthStatusNoAuthRequiredHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type GetHealthStatusNoAuthRequiredHealthGetResponses = {
  /**
   * Successful Response
   */
  200: HealthResponse;
};

export type GetHealthStatusNoAuthRequiredHealthGetResponse =
  GetHealthStatusNoAuthRequiredHealthGetResponses[keyof GetHealthStatusNoAuthRequiredHealthGetResponses];

export type GetApiVersionNoAuthRequiredVersionGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/version";
};

export type GetApiVersionNoAuthRequiredVersionGetResponses = {
  /**
   * Successful Response
   */
  200: VersionResponse;
};

export type GetApiVersionNoAuthRequiredVersionGetResponse =
  GetApiVersionNoAuthRequiredVersionGetResponses[keyof GetApiVersionNoAuthRequiredVersionGetResponses];

export type GetReadinessStatusNoAuthRequiredReadyGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ready";
};

export type GetReadinessStatusNoAuthRequiredReadyGetResponses = {
  /**
   * Successful Response
   */
  200: HealthResponse;
};

export type GetReadinessStatusNoAuthRequiredReadyGetResponse =
  GetReadinessStatusNoAuthRequiredReadyGetResponses[keyof GetReadinessStatusNoAuthRequiredReadyGetResponses];

export type GetUserIdFromEmailAuthRequiredGetUserIdPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/get-user-id";
};

export type GetUserIdFromEmailAuthRequiredGetUserIdPostResponses = {
  /**
   * Successful Response
   */
  200: UserIdResponse;
};

export type GetUserIdFromEmailAuthRequiredGetUserIdPostResponse =
  GetUserIdFromEmailAuthRequiredGetUserIdPostResponses[keyof GetUserIdFromEmailAuthRequiredGetUserIdPostResponses];

export type GetPipelinesAuthRequiredPipelinesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/pipelines";
};

export type GetPipelinesAuthRequiredPipelinesGetResponses = {
  /**
   * Successful Response
   */
  200: PipelinesResponse;
};

export type GetPipelinesAuthRequiredPipelinesGetResponse =
  GetPipelinesAuthRequiredPipelinesGetResponses[keyof GetPipelinesAuthRequiredPipelinesGetResponses];

export type GetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetData =
  {
    body?: never;
    path?: never;
    query?: never;
    url: "/model-endpoints-metadata";
  };

export type GetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetResponses =
  {
    /**
     * Successful Response
     */
    200: ModelEndpointsMetadataResponse;
  };

export type GetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetResponse =
  GetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetResponses[keyof GetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetResponses];

export type GetSeedDataAuthRequiredSeedsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/seeds";
};

export type GetSeedDataAuthRequiredSeedsGetResponses = {
  /**
   * Successful Response
   */
  200: SeedDataResponse;
};

export type GetSeedDataAuthRequiredSeedsGetResponse =
  GetSeedDataAuthRequiredSeedsGetResponses[keyof GetSeedDataAuthRequiredSeedsGetResponses];

export type GetAllDevicesAuthRequiredDevicesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/devices";
};

export type GetAllDevicesAuthRequiredDevicesGetResponses = {
  /**
   * Successful Response
   */
  200: DevicesResponse;
};

export type GetAllDevicesAuthRequiredDevicesGetResponse =
  GetAllDevicesAuthRequiredDevicesGetResponses[keyof GetAllDevicesAuthRequiredDevicesGetResponses];

export type GetDirectoriesAuthRequiredGetDirectoriesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/get-directories";
};

export type GetDirectoriesAuthRequiredGetDirectoriesGetResponses = {
  /**
   * Successful Response
   */
  200: DirectoriesResponse;
};

export type GetDirectoriesAuthRequiredGetDirectoriesGetResponse =
  GetDirectoriesAuthRequiredGetDirectoriesGetResponses[keyof GetDirectoriesAuthRequiredGetDirectoriesGetResponses];

export type CreateOrGetFolderAuthRequiredFoldersPostData = {
  body: CreateOrGetFolderRequest;
  path?: never;
  query?: never;
  url: "/folders";
};

export type CreateOrGetFolderAuthRequiredFoldersPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateOrGetFolderAuthRequiredFoldersPostError =
  CreateOrGetFolderAuthRequiredFoldersPostErrors[keyof CreateOrGetFolderAuthRequiredFoldersPostErrors];

export type CreateOrGetFolderAuthRequiredFoldersPostResponses = {
  /**
   * Successful Response
   */
  200: CreateFolderResponse;
};

export type CreateOrGetFolderAuthRequiredFoldersPostResponse =
  CreateOrGetFolderAuthRequiredFoldersPostResponses[keyof CreateOrGetFolderAuthRequiredFoldersPostResponses];

export type DeleteFolderAuthRequiredFoldersFolderIdDeleteData = {
  body?: never;
  path: {
    /**
     * Folder Id
     */
    folder_id: string;
  };
  query?: never;
  url: "/folders/{folder_id}";
};

export type DeleteFolderAuthRequiredFoldersFolderIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteFolderAuthRequiredFoldersFolderIdDeleteError =
  DeleteFolderAuthRequiredFoldersFolderIdDeleteErrors[keyof DeleteFolderAuthRequiredFoldersFolderIdDeleteErrors];

export type DeleteFolderAuthRequiredFoldersFolderIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: DeleteFolderResponse;
};

export type DeleteFolderAuthRequiredFoldersFolderIdDeleteResponse =
  DeleteFolderAuthRequiredFoldersFolderIdDeleteResponses[keyof DeleteFolderAuthRequiredFoldersFolderIdDeleteResponses];

export type UpdateFolderAuthRequiredFoldersFolderIdPutData = {
  body: UpdateFolderRequest;
  path: {
    /**
     * Folder Id
     */
    folder_id: string;
  };
  query?: never;
  url: "/folders/{folder_id}";
};

export type UpdateFolderAuthRequiredFoldersFolderIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateFolderAuthRequiredFoldersFolderIdPutError =
  UpdateFolderAuthRequiredFoldersFolderIdPutErrors[keyof UpdateFolderAuthRequiredFoldersFolderIdPutErrors];

export type UpdateFolderAuthRequiredFoldersFolderIdPutResponses = {
  /**
   * Successful Response
   */
  200: UpdateFolderResponse;
};

export type UpdateFolderAuthRequiredFoldersFolderIdPutResponse =
  UpdateFolderAuthRequiredFoldersFolderIdPutResponses[keyof UpdateFolderAuthRequiredFoldersFolderIdPutResponses];

export type CheckIfUserIsRegisteredAuthRequiredIsRegisteredGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/is-registered";
};

export type CheckIfUserIsRegisteredAuthRequiredIsRegisteredGetResponses = {
  /**
   * Successful Response
   */
  200: RegistrationStatusResponse;
};

export type CheckIfUserIsRegisteredAuthRequiredIsRegisteredGetResponse =
  CheckIfUserIsRegisteredAuthRequiredIsRegisteredGetResponses[keyof CheckIfUserIsRegisteredAuthRequiredIsRegisteredGetResponses];

export type LogoutUserNoAuthRequiredLogoutGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/logout";
};

export type LogoutUserNoAuthRequiredLogoutGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type FrontendLogEndpointAuthRequiredLogsPostData = {
  body: FrontendLogRequest;
  path?: never;
  query?: never;
  url: "/logs";
};

export type FrontendLogEndpointAuthRequiredLogsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type FrontendLogEndpointAuthRequiredLogsPostError =
  FrontendLogEndpointAuthRequiredLogsPostErrors[keyof FrontendLogEndpointAuthRequiredLogsPostErrors];

export type FrontendLogEndpointAuthRequiredLogsPostResponses = {
  /**
   * Successful Response
   */
  200: LogSubmissionResponse;
};

export type FrontendLogEndpointAuthRequiredLogsPostResponse =
  FrontendLogEndpointAuthRequiredLogsPostResponses[keyof FrontendLogEndpointAuthRequiredLogsPostResponses];

export type InitializeBatchUploadAuthRequiredNewBatchImportPostData = {
  body: BatchUploadInitRequest;
  path?: never;
  query?: never;
  url: "/new-batch-import";
};

export type InitializeBatchUploadAuthRequiredNewBatchImportPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type InitializeBatchUploadAuthRequiredNewBatchImportPostError =
  InitializeBatchUploadAuthRequiredNewBatchImportPostErrors[keyof InitializeBatchUploadAuthRequiredNewBatchImportPostErrors];

export type InitializeBatchUploadAuthRequiredNewBatchImportPostResponses = {
  /**
   * Successful Response
   */
  200: BatchUploadInitResponse;
};

export type InitializeBatchUploadAuthRequiredNewBatchImportPostResponse =
  InitializeBatchUploadAuthRequiredNewBatchImportPostResponses[keyof InitializeBatchUploadAuthRequiredNewBatchImportPostResponses];

export type UploadPictureInBatchAuthRequiredUploadPicturePostData = {
  body: BatchUploadImageRequest;
  path?: never;
  query?: never;
  url: "/upload-picture";
};

export type UploadPictureInBatchAuthRequiredUploadPicturePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadPictureInBatchAuthRequiredUploadPicturePostError =
  UploadPictureInBatchAuthRequiredUploadPicturePostErrors[keyof UploadPictureInBatchAuthRequiredUploadPicturePostErrors];

export type UploadPictureInBatchAuthRequiredUploadPicturePostResponses = {
  /**
   * Successful Response
   */
  200: BatchUploadImageResponse;
};

export type UploadPictureInBatchAuthRequiredUploadPicturePostResponse =
  UploadPictureInBatchAuthRequiredUploadPicturePostResponses[keyof UploadPictureInBatchAuthRequiredUploadPicturePostResponses];
