// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * BatchUploadImageRequest
 *
 * Upload single image in batch.
 *
 * This request is submitted for each image in the batch session.
 * The image goes through the full security pipeline (Defender scan + sanitization).
 * Duplicate images (same SHA256 hash) are tracked but not saved.
 */
export const zBatchUploadImageRequest = z
  .object({
    sessionId: z.string().register(z.globalRegistry, {
      description: "Session UUID from /new-batch-import",
    }),
    seedId: z.string().register(z.globalRegistry, {
      description: "UUID of existing seed record",
    }),
    trayCode: z.enum(["A", "B", "C", "D", "E"]),
    sampleId: z.string().min(1).max(100).register(z.globalRegistry, {
      description: "Becomes picture.name",
    }),
    imageDescription: z.string().max(500).register(z.globalRegistry, {
      description: "Description for the image",
    }),
    deviceBrandId: z.string(),
    deviceModelId: z.string(),
    deviceLensId: z.string(),
    magnification: z.number().gt(0.1).lt(1000),
    image: z.string().register(z.globalRegistry, {
      description: "Base64 data URL",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Upload single image in batch.\n\nThis request is submitted for each image in the batch session.\nThe image goes through the full security pipeline (Defender scan + sanitization).\nDuplicate images (same SHA256 hash) are tracked but not saved.",
  });

export type BatchUploadImageRequestZodType = z.infer<
  typeof zBatchUploadImageRequest
>;

/**
 * BatchUploadImageResponse
 *
 * Response from image upload - ASYNC WORKFLOW PATTERN.
 *
 * The image is queued for processing in the background.
 * Frontend must poll GET /workflow/{workflow_id}/status for completion.
 */
export const zBatchUploadImageResponse = z
  .object({
    success: z.boolean(),
    pictureId: z.optional(z.union([z.string(), z.null()])),
    workflowId: z.optional(z.union([z.string(), z.null()])),
    error: z.optional(z.union([z.string(), z.null()])),
  })
  .register(z.globalRegistry, {
    description:
      "Response from image upload - ASYNC WORKFLOW PATTERN.\n\nThe image is queued for processing in the background.\nFrontend must poll GET /workflow/{workflow_id}/status for completion.",
  });

export type BatchUploadImageResponseZodType = z.infer<
  typeof zBatchUploadImageResponse
>;

/**
 * BatchUploadInitRequest
 *
 * Initialize batch upload session.
 *
 * The folder must exist before batch upload starts.
 * Returns a session_id for subsequent upload requests.
 * Sessions expire after 24 hours and support up to 1000 files.
 */
export const zBatchUploadInitRequest = z
  .object({
    folderId: z.string().register(z.globalRegistry, {
      description: "UUID of existing folder",
    }),
    fileCount: z.int().gt(0).lte(1000).register(z.globalRegistry, {
      description: "Number of files to upload (max 1000)",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Initialize batch upload session.\n\nThe folder must exist before batch upload starts.\nReturns a session_id for subsequent upload requests.\nSessions expire after 24 hours and support up to 1000 files.",
  });

export type BatchUploadInitRequestZodType = z.infer<
  typeof zBatchUploadInitRequest
>;

/**
 * BatchUploadInitResponse
 *
 * Response from batch initialization.
 *
 * Session expires after 24 hours and accepts up to file_count uploads.
 */
export const zBatchUploadInitResponse = z
  .object({
    sessionId: z.string().register(z.globalRegistry, {
      description: "UUID of created session",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Response from batch initialization.\n\nSession expires after 24 hours and accepts up to file_count uploads.",
  });

export type BatchUploadInitResponseZodType = z.infer<
  typeof zBatchUploadInitResponse
>;

/**
 * BlobUrls
 *
 * Blob storage URLs for original and sanitized images.
 */
export const zBlobUrls = z
  .object({
    original: z.optional(z.union([z.string(), z.null()])),
    sanitized: z.optional(z.union([z.string(), z.null()])),
  })
  .register(z.globalRegistry, {
    description: "Blob storage URLs for original and sanitized images.",
  });

export type BlobUrlsZodType = z.infer<typeof zBlobUrls>;

/**
 * CreateFolderResponse
 *
 * Response model for folder creation (get-or-create pattern).
 */
export const zCreateFolderResponse = z
  .object({
    folderId: z.string().register(z.globalRegistry, {
      description: "UUID of existing or newly created folder",
    }),
  })
  .register(z.globalRegistry, {
    description: "Response model for folder creation (get-or-create pattern).",
  });

export type CreateFolderResponseZodType = z.infer<typeof zCreateFolderResponse>;

/**
 * CreateOrGetFolderRequest
 *
 * Request model for creating or retrieving a folder.
 *
 * The normalized_path is a relative path (e.g., 'avena-fatua' or 'mycology/avena-fatua').
 * The backend will prepend the user's organization prefix automatically.
 *
 * Validation is performed in the service layer via DirectoryService._validate_and_parse_fullpath().
 *
 * The description field is optional and defaults to empty string if not provided.
 */
export const zCreateOrGetFolderRequest = z
  .object({
    normalizedPath: z.string(),
    description: z.optional(z.string()).default(""),
  })
  .register(z.globalRegistry, {
    description:
      "Request model for creating or retrieving a folder.\n\nThe normalized_path is a relative path (e.g., 'avena-fatua' or 'mycology/avena-fatua').\nThe backend will prepend the user's organization prefix automatically.\n\nValidation is performed in the service layer via DirectoryService._validate_and_parse_fullpath().\n\nThe description field is optional and defaults to empty string if not provided.",
  });

export type CreateOrGetFolderRequestZodType = z.infer<
  typeof zCreateOrGetFolderRequest
>;

/**
 * DefenderScanResult
 *
 * Microsoft Defender for Storage scan result.
 */
export const zDefenderScanResult = z
  .object({
    status: z.string(),
    tags: z.record(z.string(), z.unknown()),
    scanTimestamp: z.string(),
  })
  .register(z.globalRegistry, {
    description: "Microsoft Defender for Storage scan result.",
  });

export type DefenderScanResultZodType = z.infer<typeof zDefenderScanResult>;

/**
 * DeleteFolderResponse
 *
 * Response model for folder deletion (soft delete).
 */
export const zDeleteFolderResponse = z
  .object({
    id: z.string().register(z.globalRegistry, {
      description: "UUID of the deleted folder",
    }),
    message: z.string().register(z.globalRegistry, {
      description: "Success message",
    }),
  })
  .register(z.globalRegistry, {
    description: "Response model for folder deletion (soft delete).",
  });

export type DeleteFolderResponseZodType = z.infer<typeof zDeleteFolderResponse>;

/**
 * DeviceLens
 *
 * Device lens entry.
 */
export const zDeviceLens = z
  .object({
    id: z.string().register(z.globalRegistry, {
      description: "UUID of the device lens",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Lens name",
    }),
    description: z.string().register(z.globalRegistry, {
      description: "Lens description",
    }),
  })
  .register(z.globalRegistry, {
    description: "Device lens entry.",
  });

export type DeviceLensZodType = z.infer<typeof zDeviceLens>;

/**
 * DeviceModel
 *
 * Device model entry.
 */
export const zDeviceModel = z
  .object({
    id: z.string().register(z.globalRegistry, {
      description: "UUID of the device model",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Model name",
    }),
    description: z.string().register(z.globalRegistry, {
      description: "Model description",
    }),
  })
  .register(z.globalRegistry, {
    description: "Device model entry.",
  });

export type DeviceModelZodType = z.infer<typeof zDeviceModel>;

/**
 * DeviceBrand
 *
 * Device brand with associated models and lenses.
 *
 * Represents a manufacturer brand with its available models and lenses.
 */
export const zDeviceBrand = z
  .object({
    id: z.string().register(z.globalRegistry, {
      description: "UUID of the device brand",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Brand name",
    }),
    description: z.string().register(z.globalRegistry, {
      description: "Brand description",
    }),
    models: z.array(zDeviceModel).register(z.globalRegistry, {
      description: "List of models for this brand",
    }),
    lenses: z.array(zDeviceLens).register(z.globalRegistry, {
      description: "List of lenses for this brand",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Device brand with associated models and lenses.\n\nRepresents a manufacturer brand with its available models and lenses.",
  });

export type DeviceBrandZodType = z.infer<typeof zDeviceBrand>;

/**
 * DeviceData
 *
 * Wrapper for device data list.
 */
export const zDeviceData = z
  .object({
    devices: z.array(zDeviceBrand).register(z.globalRegistry, {
      description: "List of device brands",
    }),
  })
  .register(z.globalRegistry, {
    description: "Wrapper for device data list.",
  });

export type DeviceDataZodType = z.infer<typeof zDeviceData>;

/**
 * DevicesResponse
 *
 * Response model for GET /devices endpoint.
 *
 * Returns device information (brands, models, lenses) for image metadata.
 * Uses RootModel wrapping DeviceData for proper camelCase serialization.
 */
export const zDevicesResponse = zDeviceData;

export type DevicesResponseZodType = z.infer<typeof zDevicesResponse>;

/**
 * DirectoryItem
 *
 * Individual directory/folder entry.
 *
 * Represents a user's folder with picture count and metadata.
 */
export const zDirectoryItem = z
  .object({
    id: z.string().register(z.globalRegistry, {
      description: "UUID of the directory",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Directory name",
    }),
    folderPrefix: z.string().register(z.globalRegistry, {
      description: "Organization prefix for the folder",
    }),
    description: z.string().register(z.globalRegistry, {
      description: "Directory description",
    }),
    pictureCount: z.int().register(z.globalRegistry, {
      description: "Number of pictures in this directory",
    }),
    isDefaultFolder: z.boolean().register(z.globalRegistry, {
      description: "Whether this is the user's default folder",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Individual directory/folder entry.\n\nRepresents a user's folder with picture count and metadata.",
  });

export type DirectoryItemZodType = z.infer<typeof zDirectoryItem>;

/**
 * DirectoryData
 *
 * Wrapper for directory data list.
 */
export const zDirectoryData = z
  .object({
    directories: z.array(zDirectoryItem).register(z.globalRegistry, {
      description: "List of user directories",
    }),
  })
  .register(z.globalRegistry, {
    description: "Wrapper for directory data list.",
  });

export type DirectoryDataZodType = z.infer<typeof zDirectoryData>;

/**
 * DirectoriesResponse
 *
 * Response model for GET /get-directories endpoint.
 *
 * Returns user's directory/folder tree structure.
 * Uses RootModel wrapping DirectoryData for proper camelCase serialization.
 */
export const zDirectoriesResponse = zDirectoryData;

export type DirectoriesResponseZodType = z.infer<typeof zDirectoriesResponse>;

/**
 * FrontendLogRequest
 *
 * Request model for frontend log submission.
 *
 * Frontend sends error logs to backend for centralized logging.
 * All fields are validated to prevent abuse (e.g., extremely long strings).
 */
export const zFrontendLogRequest = z
  .object({
    level: z.optional(
      z.enum(["ERROR", "WARNING", "INFO"]).register(z.globalRegistry, {
        description: "Log level",
      }),
    ),
    message: z.string().max(1000).register(z.globalRegistry, {
      description: "Log message",
    }),
    errorType: z.optional(z.union([z.string().max(200), z.null()])),
    stackTrace: z.optional(z.union([z.string().max(5000), z.null()])),
    url: z.optional(z.union([z.string().max(500), z.null()])),
    correlationId: z.optional(z.union([z.string().max(100), z.null()])),
    sessionId: z.optional(z.union([z.string().max(100), z.null()])),
  })
  .register(z.globalRegistry, {
    description:
      "Request model for frontend log submission.\n\nFrontend sends error logs to backend for centralized logging.\nAll fields are validated to prevent abuse (e.g., extremely long strings).",
  });

export type FrontendLogRequestZodType = z.infer<typeof zFrontendLogRequest>;

/**
 * HealthResponse
 *
 * Response model for GET /health and GET /ready endpoints.
 *
 * Simple health check response indicating the service is operational.
 */
export const zHealthResponse = z
  .object({
    status: z.string().register(z.globalRegistry, {
      description: "Health status (e.g., 'ok', 'ready')",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Response model for GET /health and GET /ready endpoints.\n\nSimple health check response indicating the service is operational.",
  });

export type HealthResponseZodType = z.infer<typeof zHealthResponse>;

/**
 * ImageSubmissionResponse
 *
 * Response model for image submission to processing pipeline.
 */
export const zImageSubmissionResponse = z
  .object({
    imageId: z.string(),
    workflowId: z.string(),
    status: z.string(),
    message: z.string(),
  })
  .register(z.globalRegistry, {
    description: "Response model for image submission to processing pipeline.",
  });

export type ImageSubmissionResponseZodType = z.infer<
  typeof zImageSubmissionResponse
>;

/**
 * InferenceRequestPayload
 *
 * Payload for inference workflow request.
 */
export const zInferenceRequestPayload = z
  .object({
    pictureId: z.string(),
    pipelineId: z.string(),
    imageDims: z.array(z.int()),
    workflowId: z.string(),
  })
  .register(z.globalRegistry, {
    description: "Payload for inference workflow request.",
  });

export type InferenceRequestPayloadZodType = z.infer<
  typeof zInferenceRequestPayload
>;

/**
 * InferenceWorkflowStatus
 *
 * Status information for ML inference workflow.
 */
export const zInferenceWorkflowStatus = z
  .object({
    workflowId: z.string(),
    status: z.string(),
    pipelineId: z.string(),
    createdAt: z.optional(z.union([z.string(), z.null()])),
    startedAt: z.optional(z.union([z.string(), z.null()])),
    completedAt: z.optional(z.union([z.string(), z.null()])),
    failedAt: z.optional(z.union([z.string(), z.null()])),
    errorMessage: z.optional(z.union([z.string(), z.null()])),
    requestPayload: z.optional(z.union([zInferenceRequestPayload, z.null()])),
  })
  .register(z.globalRegistry, {
    description: "Status information for ML inference workflow.",
  });

export type InferenceWorkflowStatusZodType = z.infer<
  typeof zInferenceWorkflowStatus
>;

/**
 * LogSubmissionResponse
 *
 * Response model for frontend log submission.
 *
 * Confirms that the log was received and processed.
 */
export const zLogSubmissionResponse = z
  .object({
    status: z.string().register(z.globalRegistry, {
      description: "Processing status (e.g., 'success', 'logged')",
    }),
    message: z.optional(z.union([z.string(), z.null()])),
  })
  .register(z.globalRegistry, {
    description:
      "Response model for frontend log submission.\n\nConfirms that the log was received and processed.",
  });

export type LogSubmissionResponseZodType = z.infer<
  typeof zLogSubmissionResponse
>;

/**
 * ModelInfo
 *
 * Model information for API response.
 */
export const zModelInfo = z
  .object({
    name: z.string(),
    version: z.string(),
  })
  .register(z.globalRegistry, {
    description: "Model information for API response.",
  });

export type ModelInfoZodType = z.infer<typeof zModelInfo>;

/**
 * ParentWorkflowStatus
 *
 * Status information for parent (orchestrator) workflow.
 */
export const zParentWorkflowStatus = z
  .object({
    workflowId: z.string(),
    status: z.string(),
    progressPercentage: z.optional(z.union([z.int(), z.null()])),
    createdAt: z.optional(z.union([z.string(), z.null()])),
    completedAt: z.optional(z.union([z.string(), z.null()])),
    failedAt: z.optional(z.union([z.string(), z.null()])),
    errorMessage: z.optional(z.union([z.string(), z.null()])),
    malwareDetected: z.optional(z.union([z.boolean(), z.null()])),
  })
  .register(z.globalRegistry, {
    description: "Status information for parent (orchestrator) workflow.",
  });

export type ParentWorkflowStatusZodType = z.infer<typeof zParentWorkflowStatus>;

/**
 * PipelineMetadata
 *
 * Model for individual pipeline metadata entry.
 *
 * Contains pipeline configuration, model information, and metadata.
 */
export const zPipelineMetadata = z
  .object({
    createdBy: z.string().register(z.globalRegistry, {
      description: "Creator of the pipeline",
    }),
    creationDate: z.string().register(z.globalRegistry, {
      description: "ISO formatted creation date",
    }),
    dataset: z.string().register(z.globalRegistry, {
      description: "Dataset used for training",
    }),
    description: z.string().register(z.globalRegistry, {
      description: "Pipeline description",
    }),
    identifiable: z.optional(
      z.array(z.string()).register(z.globalRegistry, {
        description: "List of identifiable classes",
      }),
    ),
    jobName: z.string().register(z.globalRegistry, {
      description: "Job name for the pipeline",
    }),
    metrics: z.optional(
      z.array(z.record(z.string(), z.unknown())).register(z.globalRegistry, {
        description: "Performance metrics",
      }),
    ),
    modelName: z.string().register(z.globalRegistry, {
      description: "Model display name",
    }),
    models: z.array(z.string()).register(z.globalRegistry, {
      description: "List of model names in the pipeline",
    }),
    pipelineName: z.string().register(z.globalRegistry, {
      description: "Pipeline name",
    }),
    pipelineId: z.string().register(z.globalRegistry, {
      description: "Pipeline UUID",
    }),
    version: z.string().register(z.globalRegistry, {
      description: "Pipeline version",
    }),
    default: z
      .optional(
        z.boolean().register(z.globalRegistry, {
          description: "Whether this is the default pipeline",
        }),
      )
      .default(false),
  })
  .register(z.globalRegistry, {
    description:
      "Model for individual pipeline metadata entry.\n\nContains pipeline configuration, model information, and metadata.",
  });

export type PipelineMetadataZodType = z.infer<typeof zPipelineMetadata>;

/**
 * ModelEndpointsMetadataResponse
 *
 * Response model for GET /model-endpoints-metadata endpoint.
 *
 * Returns ML model endpoint configuration metadata.
 * Uses RootModel to return a list of PipelineMetadata objects.
 */
export const zModelEndpointsMetadataResponse = z
  .array(zPipelineMetadata)
  .register(z.globalRegistry, {
    description:
      "Response model for GET /model-endpoints-metadata endpoint.\n\nReturns ML model endpoint configuration metadata.\nUses RootModel to return a list of PipelineMetadata objects.",
  });

export type ModelEndpointsMetadataResponseZodType = z.infer<
  typeof zModelEndpointsMetadataResponse
>;

/**
 * PipelineStep
 *
 * Individual model step in a pipeline.
 *
 * Represents a single ML model within a pipeline's execution sequence.
 */
export const zPipelineStep = z
  .object({
    modelId: z.string().register(z.globalRegistry, {
      description: "UUID of the model",
    }),
    modelName: z.string().register(z.globalRegistry, {
      description: "Name of the model",
    }),
    version: z.string().register(z.globalRegistry, {
      description: "Model version",
    }),
    endpoint: z.string().register(z.globalRegistry, {
      description: "API endpoint URL",
    }),
    apiKey: z.string().register(z.globalRegistry, {
      description: "API key for authentication",
    }),
    contentType: z.string().register(z.globalRegistry, {
      description: "Content type for requests",
    }),
    deploymentPlatform: z.string().register(z.globalRegistry, {
      description: "Platform where model is deployed",
    }),
    endpointName: z.string().register(z.globalRegistry, {
      description: "Endpoint identifier name",
    }),
    requestFunction: z.string().register(z.globalRegistry, {
      description: "Function used to make requests",
    }),
    step: z.int().register(z.globalRegistry, {
      description: "Step number in the pipeline sequence",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Individual model step in a pipeline.\n\nRepresents a single ML model within a pipeline's execution sequence.",
  });

export type PipelineStepZodType = z.infer<typeof zPipelineStep>;

/**
 * PipelineDetail
 *
 * Complete pipeline configuration with metadata and steps.
 *
 * Represents a single ML pipeline with all its models and metadata.
 */
export const zPipelineDetail = z
  .object({
    pipelineId: z.string().register(z.globalRegistry, {
      description: "UUID of the pipeline",
    }),
    pipelineName: z.string().register(z.globalRegistry, {
      description: "Pipeline name",
    }),
    createdBy: z.optional(z.union([z.string(), z.null()])),
    creationDate: z.optional(z.union([z.string(), z.null()])),
    description: z.optional(z.union([z.string(), z.null()])),
    jobName: z.optional(z.union([z.string(), z.null()])),
    version: z.optional(z.union([z.string(), z.null()])),
    dataset: z.optional(z.union([z.string(), z.null()])),
    identifiable: z.optional(
      z.array(z.string()).register(z.globalRegistry, {
        description: "List of identifiable classes",
      }),
    ),
    metrics: z.optional(
      z.array(z.record(z.string(), z.unknown())).register(z.globalRegistry, {
        description: "Performance metrics",
      }),
    ),
    models: z.array(zPipelineStep).register(z.globalRegistry, {
      description: "Ordered list of model steps in the pipeline",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Complete pipeline configuration with metadata and steps.\n\nRepresents a single ML pipeline with all its models and metadata.",
  });

export type PipelineDetailZodType = z.infer<typeof zPipelineDetail>;

/**
 * PipelinesResponse
 *
 * Response model for GET /pipelines endpoint.
 *
 * Returns available ML pipelines for seed classification.
 */
export const zPipelinesResponse = z
  .object({
    pipelines: z.array(zPipelineDetail).register(z.globalRegistry, {
      description: "List of available pipeline configurations",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Response model for GET /pipelines endpoint.\n\nReturns available ML pipelines for seed classification.",
  });

export type PipelinesResponseZodType = z.infer<typeof zPipelinesResponse>;

/**
 * PixelBoundingBox
 *
 * Bounding box coordinates in pixel values.
 *
 * Used after converting from normalized coordinates (0.0-1.0)
 * to absolute pixel positions.
 */
export const zPixelBoundingBox = z
  .object({
    topX: z.int().register(z.globalRegistry, {
      description: "Top-left X coordinate (pixels)",
    }),
    topY: z.int().register(z.globalRegistry, {
      description: "Top-left Y coordinate (pixels)",
    }),
    bottomX: z.int().register(z.globalRegistry, {
      description: "Bottom-right X coordinate (pixels)",
    }),
    bottomY: z.int().register(z.globalRegistry, {
      description: "Bottom-right Y coordinate (pixels)",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Bounding box coordinates in pixel values.\n\nUsed after converting from normalized coordinates (0.0-1.0)\nto absolute pixel positions.",
  });

export type PixelBoundingBoxZodType = z.infer<typeof zPixelBoundingBox>;

/**
 * ProcessingStages
 *
 * Processing pipeline stages completion status.
 */
export const zProcessingStages = z
  .object({
    uploaded: z.boolean(),
    defenderScanning: z.boolean(),
    defenderScanned: z.boolean(),
    sanitizing: z.boolean(),
    sanitized: z.boolean(),
  })
  .register(z.globalRegistry, {
    description: "Processing pipeline stages completion status.",
  });

export type ProcessingStagesZodType = z.infer<typeof zProcessingStages>;

/**
 * ProcessingTimestamps
 *
 * Timestamps for each processing stage.
 */
export const zProcessingTimestamps = z
  .object({
    uploadedAt: z.optional(z.union([z.string(), z.null()])),
    defenderScanStartedAt: z.optional(z.union([z.string(), z.null()])),
    defenderScanCompletedAt: z.optional(z.union([z.string(), z.null()])),
    sanitizationStartedAt: z.optional(z.union([z.string(), z.null()])),
    sanitizationCompletedAt: z.optional(z.union([z.string(), z.null()])),
    completedAt: z.optional(z.union([z.string(), z.null()])),
    failedAt: z.optional(z.union([z.string(), z.null()])),
  })
  .register(z.globalRegistry, {
    description: "Timestamps for each processing stage.",
  });

export type ProcessingTimestampsZodType = z.infer<typeof zProcessingTimestamps>;

/**
 * ProcessingWorkflowStatus
 *
 * Detailed status for image processing workflow.
 */
export const zProcessingWorkflowStatus = z
  .object({
    status: z.string(),
    stages: zProcessingStages,
    timestamps: zProcessingTimestamps,
    defenderScanResult: z.optional(z.union([zDefenderScanResult, z.null()])),
    blobUrls: zBlobUrls,
    errorMessage: z.optional(z.union([z.string(), z.null()])),
    errorDetails: z.optional(z.union([z.string(), z.null()])),
  })
  .register(z.globalRegistry, {
    description: "Detailed status for image processing workflow.",
  });

export type ProcessingWorkflowStatusZodType = z.infer<
  typeof zProcessingWorkflowStatus
>;

/**
 * RateLimitTestResponse
 *
 * Response model for GET /rate-limit-test endpoint.
 *
 * Tests rate limiting functionality.
 */
export const zRateLimitTestResponse = z
  .object({
    message: z.string().register(z.globalRegistry, {
      description: "Response message",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Response model for GET /rate-limit-test endpoint.\n\nTests rate limiting functionality.",
  });

export type RateLimitTestResponseZodType = z.infer<
  typeof zRateLimitTestResponse
>;

/**
 * RegistrationStatusResponse
 *
 * Response model for GET /is-registered endpoint.
 *
 * Checks if the user is registered in the system.
 */
export const zRegistrationStatusResponse = z
  .object({
    isRegistered: z.boolean().register(z.globalRegistry, {
      description: "Whether the user is registered in the system",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Response model for GET /is-registered endpoint.\n\nChecks if the user is registered in the system.",
  });

export type RegistrationStatusResponseZodType = z.infer<
  typeof zRegistrationStatusResponse
>;

/**
 * SeedItem
 *
 * Individual seed entry with taxonomic information.
 *
 * Represents a single seed species with identification metadata.
 */
export const zSeedItem = z
  .object({
    seedId: z.string().register(z.globalRegistry, {
      description: "UUID of the seed",
    }),
    nameCode: z.string().register(z.globalRegistry, {
      description: "Short code name for the seed",
    }),
    family: z.string().register(z.globalRegistry, {
      description: "Taxonomic family",
    }),
    genus: z.string().register(z.globalRegistry, {
      description: "Taxonomic genus",
    }),
    species: z.string().register(z.globalRegistry, {
      description: "Taxonomic species",
    }),
    seedMetadata: z.optional(
      z.union([z.record(z.string(), z.unknown()), z.null()]),
    ),
  })
  .register(z.globalRegistry, {
    description:
      "Individual seed entry with taxonomic information.\n\nRepresents a single seed species with identification metadata.",
  });

export type SeedItemZodType = z.infer<typeof zSeedItem>;

/**
 * SeedData
 *
 * Wrapper for seed data list.
 */
export const zSeedData = z
  .object({
    seeds: z.array(zSeedItem).register(z.globalRegistry, {
      description: "List of seed species",
    }),
  })
  .register(z.globalRegistry, {
    description: "Wrapper for seed data list.",
  });

export type SeedDataZodType = z.infer<typeof zSeedData>;

/**
 * SeedDataResponse
 *
 * Response model for GET /seeds endpoint.
 *
 * Returns seed species data for frontend selection.
 * Uses RootModel wrapping SeedData for proper camelCase serialization.
 */
export const zSeedDataResponse = zSeedData;

export type SeedDataResponseZodType = z.infer<typeof zSeedDataResponse>;

/**
 * TopNPredictionCleaned
 *
 * Top-N prediction with cleaned label (index prefix removed).
 */
export const zTopNPredictionCleaned = z
  .object({
    label: z.string().register(z.globalRegistry, {
      description: "Classification label without index prefix",
    }),
    score: z.number().gte(0).lte(1).register(z.globalRegistry, {
      description: "Confidence score",
    }),
  })
  .register(z.globalRegistry, {
    description: "Top-N prediction with cleaned label (index prefix removed).",
  });

export type TopNPredictionCleanedZodType = z.infer<
  typeof zTopNPredictionCleaned
>;

/**
 * ApiInferenceBox
 *
 * Inference box matching frontend InferenceBoxApiSchema.
 *
 * This is the exact format expected by the frontend for each box in the inference results.
 * Includes all required fields for frontend visualization and interaction.
 *
 * Note: Frontend expects PIXEL coordinates, not normalized coordinates!
 */
export const zApiInferenceBox = z
  .object({
    box: zPixelBoundingBox,
    label: z.string().register(z.globalRegistry, {
      description: "Primary classification label",
    }),
    score: z.number().gte(0).lte(1).register(z.globalRegistry, {
      description: "Confidence score",
    }),
    topN: z.array(zTopNPredictionCleaned).register(z.globalRegistry, {
      description: "Top-N predictions",
    }),
    classId: z.string().register(z.globalRegistry, {
      description: "Unique identifier for this classification",
    }),
    objectTypeId: z.string().register(z.globalRegistry, {
      description: "Type identifier for the detected object",
    }),
    boxId: z.string().register(z.globalRegistry, {
      description: "Unique identifier for this bounding box",
    }),
    overlapping: z.boolean().register(z.globalRegistry, {
      description: "Whether this box overlaps with others",
    }),
    overlappingIndices: z.int().register(z.globalRegistry, {
      description: "Index of overlapping box (if any), -1 if none",
    }),
    isVerified: z
      .optional(
        z.boolean().register(z.globalRegistry, {
          description: "Whether this box has been verified by user",
        }),
      )
      .default(false),
  })
  .register(z.globalRegistry, {
    description:
      "Inference box matching frontend InferenceBoxApiSchema.\n\nThis is the exact format expected by the frontend for each box in the inference results.\nIncludes all required fields for frontend visualization and interaction.\n\nNote: Frontend expects PIXEL coordinates, not normalized coordinates!",
  });

export type ApiInferenceBoxZodType = z.infer<typeof zApiInferenceBox>;

/**
 * ApiInferenceResponse
 *
 * Complete inference response matching frontend ApiInferenceDataSchema.
 *
 * This is the format expected by the frontend for inference results.
 * Used by /inf-direct endpoint.
 */
export const zApiInferenceResponse = z
  .object({
    filename: z.string(),
    imageId: z.string().register(z.globalRegistry, {
      description: "Image UUID or identifier",
    }),
    inferenceId: z.string().register(z.globalRegistry, {
      description: "Inference UUID or identifier",
    }),
    boxes: z.array(zApiInferenceBox),
    labelOccurrence: z.record(z.string(), z.int()).register(z.globalRegistry, {
      description: "Count of each label found in the image",
    }),
    totalBoxes: z.int().register(z.globalRegistry, {
      description: "Total number of detected boxes",
    }),
    models: z.array(zModelInfo).register(z.globalRegistry, {
      description: "Models used for inference",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Complete inference response matching frontend ApiInferenceDataSchema.\n\nThis is the format expected by the frontend for inference results.\nUsed by /inf-direct endpoint.",
  });

export type ApiInferenceResponseZodType = z.infer<typeof zApiInferenceResponse>;

/**
 * TrayCode
 *
 * Valid tray codes for sample identification.
 */
export const zTrayCode = z
  .enum(["A", "B", "C", "D", "E"])
  .register(z.globalRegistry, {
    description: "Valid tray codes for sample identification.",
  });

export type TrayCodeZodType = z.infer<typeof zTrayCode>;

/**
 * InferenceRequest
 *
 * Request model for POST /inf endpoint.
 *
 * Matches legacy API format for backwards compatibility.
 * Includes required image metadata fields sent by frontend.
 */
export const zInferenceRequest = z
  .object({
    pipelineId: z.string(),
    folderName: z.string(),
    folderId: z.string(),
    imageDims: z.tuple([z.int(), z.int()]).register(z.globalRegistry, {
      description: "Image dimensions as [width, height]",
    }),
    image: z.string(),
    areaRatio: z.optional(z.number()).default(0.5),
    colorFormat: z.optional(z.string()).default("hex"),
    imageName: z.string().max(100).register(z.globalRegistry, {
      description: "Human-readable name for the image",
    }),
    imageDescription: z.string().max(500).register(z.globalRegistry, {
      description: "Description or notes about the image",
    }),
    deviceModelId: z.uuid().register(z.globalRegistry, {
      description: "UUID of the device model used to capture the image",
    }),
    deviceLensId: z.uuid().register(z.globalRegistry, {
      description: "UUID of the lens used to capture the image",
    }),
    trayCode: zTrayCode,
    magnification: z.number().register(z.globalRegistry, {
      description: "Magnification level used when capturing the image",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Request model for POST /inf endpoint.\n\nMatches legacy API format for backwards compatibility.\nIncludes required image metadata fields sent by frontend.",
  });

export type InferenceRequestZodType = z.infer<typeof zInferenceRequest>;

/**
 * UpdateFolderRequest
 *
 * Request model for updating a folder's name and/or description.
 *
 * Both fields are optional - update only the fields provided.
 * Name validation is performed in the service layer.
 * Description is sanitized on the client side.
 */
export const zUpdateFolderRequest = z
  .object({
    name: z.optional(z.union([z.string(), z.null()])),
    description: z.optional(z.union([z.string(), z.null()])),
  })
  .register(z.globalRegistry, {
    description:
      "Request model for updating a folder's name and/or description.\n\nBoth fields are optional - update only the fields provided.\nName validation is performed in the service layer.\nDescription is sanitized on the client side.",
  });

export type UpdateFolderRequestZodType = z.infer<typeof zUpdateFolderRequest>;

/**
 * UpdateFolderResponse
 *
 * Response model for folder update operations.
 */
export const zUpdateFolderResponse = z
  .object({
    id: z.string(),
    message: z.string(),
  })
  .register(z.globalRegistry, {
    description: "Response model for folder update operations.",
  });

export type UpdateFolderResponseZodType = z.infer<typeof zUpdateFolderResponse>;

/**
 * UserIdResponse
 *
 * Response model for POST /get-user-id endpoint.
 *
 * Returns the authenticated user's ID.
 */
export const zUserIdResponse = z
  .object({
    userId: z.string().register(z.globalRegistry, {
      description: "User's unique identifier (OID from Azure AD)",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Response model for POST /get-user-id endpoint.\n\nReturns the authenticated user's ID.",
  });

export type UserIdResponseZodType = z.infer<typeof zUserIdResponse>;

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
});

export type ValidationErrorZodType = z.infer<typeof zValidationError>;

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.optional(z.array(zValidationError)),
});

export type HttpValidationErrorZodType = z.infer<typeof zHttpValidationError>;

/**
 * VersionResponse
 *
 * Response model for GET /version endpoint.
 *
 * Returns the current API version.
 */
export const zVersionResponse = z
  .object({
    version: z.string().register(z.globalRegistry, {
      description: "API version string",
    }),
  })
  .register(z.globalRegistry, {
    description:
      "Response model for GET /version endpoint.\n\nReturns the current API version.",
  });

export type VersionResponseZodType = z.infer<typeof zVersionResponse>;

/**
 * WorkflowAuthorization
 *
 * Authorization metadata for workflow access.
 */
export const zWorkflowAuthorization = z
  .object({
    userId: z.string(),
    isOwner: z.boolean(),
    isCfiaAdmin: z.boolean(),
  })
  .register(z.globalRegistry, {
    description: "Authorization metadata for workflow access.",
  });

export type WorkflowAuthorizationZodType = z.infer<
  typeof zWorkflowAuthorization
>;

/**
 * WorkflowStatusResponse
 *
 * Comprehensive workflow status response.
 *
 * Returned by GET /workflow/{workflow_id}/status endpoint.
 * Provides complete status tracking for image processing and inference workflows.
 *
 * The response includes:
 * - Overall workflow status and type
 * - Parent workflow orchestration status
 * - Image processing pipeline details and timestamps
 * - ML inference workflow status
 * - Authorization metadata
 */
export const zWorkflowStatusResponse = z
  .object({
    workflowId: z.string().register(z.globalRegistry, {
      description: "The queried workflow ID",
    }),
    workflowType: z.string().register(z.globalRegistry, {
      description: "Workflow type: 'parent', 'processing', or 'inference'",
    }),
    imageId: z.string().register(z.globalRegistry, {
      description: "Associated picture UUID",
    }),
    overallStatus: z.string().register(z.globalRegistry, {
      description:
        "High-level status: 'pending', 'in_progress', 'completed', 'failed'",
    }),
    authorization: zWorkflowAuthorization,
    parentWorkflow: z.optional(z.union([zParentWorkflowStatus, z.null()])),
    processingWorkflow: z.optional(
      z.union([zProcessingWorkflowStatus, z.null()]),
    ),
    inferenceWorkflow: z.optional(
      z.union([zInferenceWorkflowStatus, z.null()]),
    ),
    errorMessage: z.optional(z.union([z.string(), z.null()])),
    errorDetails: z.optional(z.union([z.string(), z.null()])),
  })
  .register(z.globalRegistry, {
    description:
      "Comprehensive workflow status response.\n\nReturned by GET /workflow/{workflow_id}/status endpoint.\nProvides complete status tracking for image processing and inference workflows.\n\nThe response includes:\n- Overall workflow status and type\n- Parent workflow orchestration status\n- Image processing pipeline details and timestamps\n- ML inference workflow status\n- Authorization metadata",
  });

export type WorkflowStatusResponseZodType = z.infer<
  typeof zWorkflowStatusResponse
>;

export const zSubmitImageForProcessingAuthRequiredInfPostData = z.object({
  body: zInferenceRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export type SubmitImageForProcessingAuthRequiredInfPostDataZodType = z.infer<
  typeof zSubmitImageForProcessingAuthRequiredInfPostData
>;

/**
 * Successful Response
 */
export const zSubmitImageForProcessingAuthRequiredInfPostResponse =
  zImageSubmissionResponse;

export type SubmitImageForProcessingAuthRequiredInfPostResponseZodType =
  z.infer<typeof zSubmitImageForProcessingAuthRequiredInfPostResponse>;

export const zSubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostData =
  z.object({
    body: zInferenceRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
  });

export type SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostDataZodType =
  z.infer<typeof zSubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostData>;

/**
 * Successful Response
 */
export const zSubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostResponse =
  zApiInferenceResponse;

export type SubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostResponseZodType =
  z.infer<
    typeof zSubmitImageForDirectProcessingCfiaAdminOnlyInfDirectPostResponse
  >;

export const zGetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      workflow_id: z.string(),
    }),
    query: z.optional(z.never()),
  });

export type GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetDataZodType =
  z.infer<typeof zGetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetData>;

/**
 * Successful Response
 */
export const zGetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetResponse =
  zWorkflowStatusResponse;

export type GetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetResponseZodType =
  z.infer<
    typeof zGetWorkflowStatusAuthRequiredWorkflowWorkflowIdStatusGetResponse
  >;

export const zGetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      workflow_id: z.string(),
    }),
    query: z.optional(z.never()),
  });

export type GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetDataZodType =
  z.infer<
    typeof zGetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetData
  >;

/**
 * Successful Response
 */
export const zGetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetResponse =
  zApiInferenceResponse;

export type GetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetResponseZodType =
  z.infer<
    typeof zGetWorkflowResultsAuthRequiredWorkflowWorkflowIdResultsGetResponse
  >;

export const zRateLimitTestNoAuthRequiredRateLimitTestGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export type RateLimitTestNoAuthRequiredRateLimitTestGetDataZodType = z.infer<
  typeof zRateLimitTestNoAuthRequiredRateLimitTestGetData
>;

/**
 * Successful Response
 */
export const zRateLimitTestNoAuthRequiredRateLimitTestGetResponse =
  zRateLimitTestResponse;

export type RateLimitTestNoAuthRequiredRateLimitTestGetResponseZodType =
  z.infer<typeof zRateLimitTestNoAuthRequiredRateLimitTestGetResponse>;

export const zGetHealthStatusNoAuthRequiredHealthGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export type GetHealthStatusNoAuthRequiredHealthGetDataZodType = z.infer<
  typeof zGetHealthStatusNoAuthRequiredHealthGetData
>;

/**
 * Successful Response
 */
export const zGetHealthStatusNoAuthRequiredHealthGetResponse = zHealthResponse;

export type GetHealthStatusNoAuthRequiredHealthGetResponseZodType = z.infer<
  typeof zGetHealthStatusNoAuthRequiredHealthGetResponse
>;

export const zGetApiVersionNoAuthRequiredVersionGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export type GetApiVersionNoAuthRequiredVersionGetDataZodType = z.infer<
  typeof zGetApiVersionNoAuthRequiredVersionGetData
>;

/**
 * Successful Response
 */
export const zGetApiVersionNoAuthRequiredVersionGetResponse = zVersionResponse;

export type GetApiVersionNoAuthRequiredVersionGetResponseZodType = z.infer<
  typeof zGetApiVersionNoAuthRequiredVersionGetResponse
>;

export const zGetReadinessStatusNoAuthRequiredReadyGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export type GetReadinessStatusNoAuthRequiredReadyGetDataZodType = z.infer<
  typeof zGetReadinessStatusNoAuthRequiredReadyGetData
>;

/**
 * Successful Response
 */
export const zGetReadinessStatusNoAuthRequiredReadyGetResponse =
  zHealthResponse;

export type GetReadinessStatusNoAuthRequiredReadyGetResponseZodType = z.infer<
  typeof zGetReadinessStatusNoAuthRequiredReadyGetResponse
>;

export const zGetUserIdFromEmailAuthRequiredGetUserIdPostData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export type GetUserIdFromEmailAuthRequiredGetUserIdPostDataZodType = z.infer<
  typeof zGetUserIdFromEmailAuthRequiredGetUserIdPostData
>;

/**
 * Successful Response
 */
export const zGetUserIdFromEmailAuthRequiredGetUserIdPostResponse =
  zUserIdResponse;

export type GetUserIdFromEmailAuthRequiredGetUserIdPostResponseZodType =
  z.infer<typeof zGetUserIdFromEmailAuthRequiredGetUserIdPostResponse>;

export const zGetPipelinesAuthRequiredPipelinesGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export type GetPipelinesAuthRequiredPipelinesGetDataZodType = z.infer<
  typeof zGetPipelinesAuthRequiredPipelinesGetData
>;

/**
 * Successful Response
 */
export const zGetPipelinesAuthRequiredPipelinesGetResponse = zPipelinesResponse;

export type GetPipelinesAuthRequiredPipelinesGetResponseZodType = z.infer<
  typeof zGetPipelinesAuthRequiredPipelinesGetResponse
>;

export const zGetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetData =
  z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
  });

export type GetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetDataZodType =
  z.infer<
    typeof zGetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetData
  >;

/**
 * Successful Response
 */
export const zGetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetResponse =
  zModelEndpointsMetadataResponse;

export type GetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetResponseZodType =
  z.infer<
    typeof zGetModelEndpointsMetadataAuthRequiredModelEndpointsMetadataGetResponse
  >;

export const zGetSeedDataAuthRequiredSeedsGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export type GetSeedDataAuthRequiredSeedsGetDataZodType = z.infer<
  typeof zGetSeedDataAuthRequiredSeedsGetData
>;

/**
 * Successful Response
 */
export const zGetSeedDataAuthRequiredSeedsGetResponse = zSeedDataResponse;

export type GetSeedDataAuthRequiredSeedsGetResponseZodType = z.infer<
  typeof zGetSeedDataAuthRequiredSeedsGetResponse
>;

export const zGetAllDevicesAuthRequiredDevicesGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export type GetAllDevicesAuthRequiredDevicesGetDataZodType = z.infer<
  typeof zGetAllDevicesAuthRequiredDevicesGetData
>;

/**
 * Successful Response
 */
export const zGetAllDevicesAuthRequiredDevicesGetResponse = zDevicesResponse;

export type GetAllDevicesAuthRequiredDevicesGetResponseZodType = z.infer<
  typeof zGetAllDevicesAuthRequiredDevicesGetResponse
>;

export const zGetDirectoriesAuthRequiredGetDirectoriesGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export type GetDirectoriesAuthRequiredGetDirectoriesGetDataZodType = z.infer<
  typeof zGetDirectoriesAuthRequiredGetDirectoriesGetData
>;

/**
 * Successful Response
 */
export const zGetDirectoriesAuthRequiredGetDirectoriesGetResponse =
  zDirectoriesResponse;

export type GetDirectoriesAuthRequiredGetDirectoriesGetResponseZodType =
  z.infer<typeof zGetDirectoriesAuthRequiredGetDirectoriesGetResponse>;

export const zCreateOrGetFolderAuthRequiredFoldersPostData = z.object({
  body: zCreateOrGetFolderRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export type CreateOrGetFolderAuthRequiredFoldersPostDataZodType = z.infer<
  typeof zCreateOrGetFolderAuthRequiredFoldersPostData
>;

/**
 * Successful Response
 */
export const zCreateOrGetFolderAuthRequiredFoldersPostResponse =
  zCreateFolderResponse;

export type CreateOrGetFolderAuthRequiredFoldersPostResponseZodType = z.infer<
  typeof zCreateOrGetFolderAuthRequiredFoldersPostResponse
>;

export const zDeleteFolderAuthRequiredFoldersFolderIdDeleteData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    folder_id: z.string(),
  }),
  query: z.optional(z.never()),
});

export type DeleteFolderAuthRequiredFoldersFolderIdDeleteDataZodType = z.infer<
  typeof zDeleteFolderAuthRequiredFoldersFolderIdDeleteData
>;

/**
 * Successful Response
 */
export const zDeleteFolderAuthRequiredFoldersFolderIdDeleteResponse =
  zDeleteFolderResponse;

export type DeleteFolderAuthRequiredFoldersFolderIdDeleteResponseZodType =
  z.infer<typeof zDeleteFolderAuthRequiredFoldersFolderIdDeleteResponse>;

export const zUpdateFolderAuthRequiredFoldersFolderIdPutData = z.object({
  body: zUpdateFolderRequest,
  path: z.object({
    folder_id: z.string(),
  }),
  query: z.optional(z.never()),
});

export type UpdateFolderAuthRequiredFoldersFolderIdPutDataZodType = z.infer<
  typeof zUpdateFolderAuthRequiredFoldersFolderIdPutData
>;

/**
 * Successful Response
 */
export const zUpdateFolderAuthRequiredFoldersFolderIdPutResponse =
  zUpdateFolderResponse;

export type UpdateFolderAuthRequiredFoldersFolderIdPutResponseZodType = z.infer<
  typeof zUpdateFolderAuthRequiredFoldersFolderIdPutResponse
>;

export const zCheckIfUserIsRegisteredAuthRequiredIsRegisteredGetData = z.object(
  {
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
  },
);

export type CheckIfUserIsRegisteredAuthRequiredIsRegisteredGetDataZodType =
  z.infer<typeof zCheckIfUserIsRegisteredAuthRequiredIsRegisteredGetData>;

/**
 * Successful Response
 */
export const zCheckIfUserIsRegisteredAuthRequiredIsRegisteredGetResponse =
  zRegistrationStatusResponse;

export type CheckIfUserIsRegisteredAuthRequiredIsRegisteredGetResponseZodType =
  z.infer<typeof zCheckIfUserIsRegisteredAuthRequiredIsRegisteredGetResponse>;

export const zLogoutUserNoAuthRequiredLogoutGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export type LogoutUserNoAuthRequiredLogoutGetDataZodType = z.infer<
  typeof zLogoutUserNoAuthRequiredLogoutGetData
>;

export const zFrontendLogEndpointAuthRequiredLogsPostData = z.object({
  body: zFrontendLogRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export type FrontendLogEndpointAuthRequiredLogsPostDataZodType = z.infer<
  typeof zFrontendLogEndpointAuthRequiredLogsPostData
>;

/**
 * Successful Response
 */
export const zFrontendLogEndpointAuthRequiredLogsPostResponse =
  zLogSubmissionResponse;

export type FrontendLogEndpointAuthRequiredLogsPostResponseZodType = z.infer<
  typeof zFrontendLogEndpointAuthRequiredLogsPostResponse
>;

export const zInitializeBatchUploadAuthRequiredNewBatchImportPostData =
  z.object({
    body: zBatchUploadInitRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
  });

export type InitializeBatchUploadAuthRequiredNewBatchImportPostDataZodType =
  z.infer<typeof zInitializeBatchUploadAuthRequiredNewBatchImportPostData>;

/**
 * Successful Response
 */
export const zInitializeBatchUploadAuthRequiredNewBatchImportPostResponse =
  zBatchUploadInitResponse;

export type InitializeBatchUploadAuthRequiredNewBatchImportPostResponseZodType =
  z.infer<typeof zInitializeBatchUploadAuthRequiredNewBatchImportPostResponse>;

export const zUploadPictureInBatchAuthRequiredUploadPicturePostData = z.object({
  body: zBatchUploadImageRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export type UploadPictureInBatchAuthRequiredUploadPicturePostDataZodType =
  z.infer<typeof zUploadPictureInBatchAuthRequiredUploadPicturePostData>;

/**
 * Successful Response
 */
export const zUploadPictureInBatchAuthRequiredUploadPicturePostResponse =
  zBatchUploadImageResponse;

export type UploadPictureInBatchAuthRequiredUploadPicturePostResponseZodType =
  z.infer<typeof zUploadPictureInBatchAuthRequiredUploadPicturePostResponse>;
