# https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"
metadata_auto_snapshot_interval = "6h"

replication_factor = 1

# compression_level = 2

rpc_bind_addr = "[::]:12441"
rpc_public_addr = "127.0.0.1:12441"
rpc_secret = "<generate your secret by running in bash: openssl rand -hex 32>"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:12440"
root_domain = ".s3.garage.localhost"

# [s3_web]
# bind_addr = "[::]:12442"
# root_domain = ".web.garage.localhost"
# index = "index.html"

# [k2v_api]
# api_bind_addr = "[::]:12444"

[admin]
api_bind_addr = "[::]:12443"
admin_token = "<generate your secret by running in bash: openssl rand -hex 32>"
metrics_token = "<generate your secret by running in bash: openssl rand -hex 32>"
###  openssl rand -hex 32
