"""add fields to seed table

Revision ID: 2dc1198f9099
Revises: ced6fc7fc62a
Create Date: 2025-11-26 04:36:11.830692

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2dc1198f9099"
down_revision: Union[str, Sequence[str], None] = "ced6fc7fc62a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("seed", sa.Column("subspecies", sa.Text(), nullable=True))
    op.add_column("seed", sa.Column("variety", sa.Text(), nullable=True))
    op.add_column("seed", sa.Column("author", sa.Text(), nullable=True))
    op.add_column("seed", sa.Column("url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seed", "url")
    op.drop_column("seed", "author")
    op.drop_column("seed", "variety")
    op.drop_column("seed", "subspecies")
    # ### end Alembic commands ###
