"""First migration

Revision ID: ad6e5cf95fb4
Revises: 
Create Date: 2025-10-15 21:41:27.515073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6e5cf95fb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_brand',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('folder_prefix', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_name', sa.Text(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('dataset', sa.Text(), nullable=True),
    sa.Column('identifiable', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rbac_permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_rbac_permission_name')
    )
    op.create_table('rbac_resource',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_rbac_resource_name')
    )
    op.create_table('seed',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name_code', sa.Text(), nullable=False),
    sa.Column('family', sa.Text(), nullable=False),
    sa.Column('genus', sa.Text(), nullable=False),
    sa.Column('species', sa.Text(), nullable=False),
    sa.Column('original_ista_2025', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_family'), 'seed', ['family'], unique=False)
    op.create_index(op.f('ix_seed_genus'), 'seed', ['genus'], unique=False)
    op.create_index(op.f('ix_seed_species'), 'seed', ['species'], unique=False)
    op.create_table('device_lens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_brand_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_brand_id'], ['device_brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_brand_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_brand_id'], ['device_brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_model_training', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('deployment_platform', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('endpoint_name', sa.Text(), nullable=False),
    sa.Column('api_url', sa.Text(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_name', sa.Text(), nullable=True, comment='Training job name'),
    sa.Column('dataset', sa.Text(), nullable=True, comment='training dataset id'),
    sa.Column('artifacts_url', sa.Text(), nullable=True),
    sa.Column('sha256', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['model_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_default',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id')
    )
    op.create_table('rbac_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_rbac_role_org_name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('default_folder_id', sa.UUID(), nullable=True),
    sa.Column('organization', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('table', sa.Text(), nullable=True),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('action_id', sa.UUID(), nullable=True),
    sa.Column('value_prev', sa.JSON(), nullable=True),
    sa.Column('value_new', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folder',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_user_role_id', sa.UUID(), nullable=False),
    sa.Column('org_admin_role_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('folder_prefix', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['org_admin_role_id'], ['rbac_role.id'], ),
    sa.ForeignKeyConstraint(['org_user_role_id'], ['rbac_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rbac_role_permission_resource',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['rbac_permission.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['rbac_resource.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', 'resource_id')
    )
    op.create_table('rbac_user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('picture',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_user_role_id', sa.UUID(), nullable=False),
    sa.Column('org_admin_role_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('blob_url_original', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('size_on_disk_original', sa.Double(), nullable=False),
    sa.Column('size_on_disk_sanitized', sa.Double(), nullable=True),
    sa.Column('magnification', sa.Double(), nullable=True),
    sa.Column('blob_url_sanitized', sa.Text(), nullable=True),
    sa.Column('device_model_id', sa.UUID(), nullable=True),
    sa.Column('device_lens_id', sa.UUID(), nullable=True),
    sa.Column('single_species_image', sa.UUID(), nullable=True, comment='for training, multiple seeds of the same species will be in the image, this value is specified by uploader, null if multi spp'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_admin_role_id'], ['rbac_role.id'], ),
    sa.ForeignKeyConstraint(['org_user_role_id'], ['rbac_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picture_sha256'), 'picture', ['sha256'], unique=False)
    op.create_table('annotation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_user_role_id', sa.UUID(), nullable=False),
    sa.Column('org_admin_role_id', sa.UUID(), nullable=False),
    sa.Column('picture_id', sa.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False, comment='pipeline used, human should be an entry in pipeline table'),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['org_admin_role_id'], ['rbac_role.id'], ),
    sa.ForeignKeyConstraint(['org_user_role_id'], ['rbac_role.id'], ),
    sa.ForeignKeyConstraint(['picture_id'], ['picture.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_user_role_id', sa.UUID(), nullable=False),
    sa.Column('org_admin_role_id', sa.UUID(), nullable=False),
    sa.Column('inference_id', sa.UUID(), nullable=False),
    sa.Column('picture_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('bot_y_abs', sa.Integer(), nullable=False),
    sa.Column('bot_x_abs', sa.Integer(), nullable=False),
    sa.Column('top_y_abs', sa.Integer(), nullable=False),
    sa.Column('top_x_abs', sa.Integer(), nullable=False),
    sa.Column('top_id', sa.UUID(), nullable=False),
    sa.Column('top_id_2', sa.UUID(), nullable=True),
    sa.Column('top_id_3', sa.UUID(), nullable=True),
    sa.Column('top_score', sa.Double(), nullable=False),
    sa.Column('top_score_2', sa.Double(), nullable=True),
    sa.Column('top_score_3', sa.Double(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_feedback', sa.DateTime(timezone=True), nullable=True),
    sa.Column('box_update', sa.Boolean(), nullable=True),
    sa.Column('species_update', sa.Boolean(), nullable=True),
    sa.Column('feedback_user_id', sa.UUID(), nullable=True),
    sa.Column('verifier_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inference_id'], ['annotation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_admin_role_id'], ['rbac_role.id'], ),
    sa.ForeignKeyConstraint(['org_user_role_id'], ['rbac_role.id'], ),
    sa.ForeignKeyConstraint(['picture_id'], ['picture.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ),
    sa.ForeignKeyConstraint(['top_id'], ['seed.id'], ),
    sa.ForeignKeyConstraint(['top_id_2'], ['seed.id'], ),
    sa.ForeignKeyConstraint(['top_id_3'], ['seed.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verifier_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('object')
    op.drop_table('annotation')
    op.drop_index(op.f('ix_picture_sha256'), table_name='picture')
    op.drop_table('picture')
    op.drop_table('rbac_user_role')
    op.drop_table('rbac_role_permission_resource')
    op.drop_table('pipeline_model')
    op.drop_table('folder')
    op.drop_table('change_log')
    op.drop_table('users')
    op.drop_table('rbac_role')
    op.drop_table('pipeline_default')
    op.drop_table('model')
    op.drop_table('device_model')
    op.drop_table('device_lens')
    op.drop_index(op.f('ix_seed_species'), table_name='seed')
    op.drop_index(op.f('ix_seed_genus'), table_name='seed')
    op.drop_index(op.f('ix_seed_family'), table_name='seed')
    op.drop_table('seed')
    op.drop_table('rbac_resource')
    op.drop_table('rbac_permission')
    op.drop_table('pipeline')
    op.drop_table('organization')
    op.drop_table('model_task')
    op.drop_table('device_brand')
    # ### end Alembic commands ###
