"""add tray code column to picture table

Revision ID: ced6fc7fc62a
Revises: c95209d9c2f7
Create Date: 2025-11-03 03:08:33.935913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ced6fc7fc62a"
down_revision: Union[str, Sequence[str], None] = "c95209d9c2f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "picture", sa.Column("tray_code", sa.Text(), nullable=False, server_default="")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("picture", "tray_code")
    # ### end Alembic commands ###
