"""add ownership to state tables

Revision ID: 284696655b6b
Revises: a4a99b3347b4
Create Date: 2025-10-29 18:05:53.946936

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "284696655b6b"
down_revision: Union[str, Sequence[str], None] = "a4a99b3347b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add columns as nullable first
    op.add_column(
        "image_processing_state",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=True,
            comment="User who initiated the workflow",
        ),
    )
    op.add_column(
        "image_processing_state",
        sa.Column(
            "org_user_role_id",
            sa.UUID(),
            nullable=True,
            comment="User's role in their organization",
        ),
    )
    op.add_column(
        "image_processing_state",
        sa.Column(
            "org_admin_role_id",
            sa.UUID(),
            nullable=True,
            comment="Admin role for cross-org access (CFIA admins)",
        ),
    )

    op.add_column(
        "inference_request_state",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=True,
            comment="User who initiated the inference request",
        ),
    )
    op.add_column(
        "inference_request_state",
        sa.Column(
            "org_user_role_id",
            sa.UUID(),
            nullable=True,
            comment="User's role in their organization",
        ),
    )
    op.add_column(
        "inference_request_state",
        sa.Column(
            "org_admin_role_id",
            sa.UUID(),
            nullable=True,
            comment="Admin role for cross-org access (CFIA admins)",
        ),
    )

    # Step 2: Backfill ownership data from picture table
    # For image_processing_state
    op.execute("""
        UPDATE image_processing_state ips
        SET
            user_id = p.user_id,
            org_user_role_id = p.org_user_role_id,
            org_admin_role_id = p.org_admin_role_id
        FROM picture p
        WHERE ips.picture_id = p.id
    """)

    # For inference_request_state
    op.execute("""
        UPDATE inference_request_state irs
        SET
            user_id = p.user_id,
            org_user_role_id = p.org_user_role_id,
            org_admin_role_id = p.org_admin_role_id
        FROM picture p
        WHERE irs.picture_id = p.id
    """)

    # Step 3: Set columns to NOT NULL
    op.alter_column("image_processing_state", "user_id", nullable=False)
    op.alter_column("image_processing_state", "org_user_role_id", nullable=False)
    op.alter_column("image_processing_state", "org_admin_role_id", nullable=False)

    op.alter_column("inference_request_state", "user_id", nullable=False)
    op.alter_column("inference_request_state", "org_user_role_id", nullable=False)
    op.alter_column("inference_request_state", "org_admin_role_id", nullable=False)

    # Step 4: Create indexes
    op.create_index(
        "idx_processing_state_user", "image_processing_state", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_image_processing_state_user_id"),
        "image_processing_state",
        ["user_id"],
        unique=False,
    )

    op.create_index(
        "idx_inference_request_state_picture",
        "inference_request_state",
        ["picture_id"],
        unique=False,
    )
    op.create_index(
        "idx_inference_request_state_user",
        "inference_request_state",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "idx_inference_request_state_workflow",
        "inference_request_state",
        ["workflow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inference_request_state_user_id"),
        "inference_request_state",
        ["user_id"],
        unique=False,
    )

    # Step 5: Create foreign keys
    op.create_foreign_key(
        None, "image_processing_state", "rbac_role", ["org_admin_role_id"], ["id"]
    )
    op.create_foreign_key(None, "image_processing_state", "users", ["user_id"], ["id"])
    op.create_foreign_key(
        None, "image_processing_state", "rbac_role", ["org_user_role_id"], ["id"]
    )

    op.create_foreign_key(None, "inference_request_state", "users", ["user_id"], ["id"])
    op.create_foreign_key(
        None, "inference_request_state", "rbac_role", ["org_admin_role_id"], ["id"]
    )
    op.create_foreign_key(
        None, "inference_request_state", "rbac_role", ["org_user_role_id"], ["id"]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "inference_request_state", type_="foreignkey")
    op.drop_constraint(None, "inference_request_state", type_="foreignkey")
    op.drop_constraint(None, "inference_request_state", type_="foreignkey")
    op.drop_index(
        op.f("ix_inference_request_state_user_id"), table_name="inference_request_state"
    )
    op.drop_index(
        "idx_inference_request_state_workflow", table_name="inference_request_state"
    )
    op.drop_index(
        "idx_inference_request_state_user", table_name="inference_request_state"
    )
    op.drop_index(
        "idx_inference_request_state_picture", table_name="inference_request_state"
    )
    op.drop_column("inference_request_state", "org_admin_role_id")
    op.drop_column("inference_request_state", "org_user_role_id")
    op.drop_column("inference_request_state", "user_id")
    op.drop_constraint(None, "image_processing_state", type_="foreignkey")
    op.drop_constraint(None, "image_processing_state", type_="foreignkey")
    op.drop_constraint(None, "image_processing_state", type_="foreignkey")
    op.drop_index(
        op.f("ix_image_processing_state_user_id"), table_name="image_processing_state"
    )
    op.drop_index("idx_processing_state_user", table_name="image_processing_state")
    op.drop_column("image_processing_state", "org_admin_role_id")
    op.drop_column("image_processing_state", "org_user_role_id")
    op.drop_column("image_processing_state", "user_id")
    # ### end Alembic commands ###
