"""Remove Redundant Fields from state tables

Revision ID: a0c6f0016e06
Revises: 284696655b6b
Create Date: 2025-10-29 18:36:02.647384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a0c6f0016e06"
down_revision: Union[str, Sequence[str], None] = "284696655b6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_processing_state_inference_status"),
        table_name="image_processing_state",
    )
    op.drop_index(
        op.f("idx_processing_state_inference_workflow"),
        table_name="image_processing_state",
    )
    op.drop_index(
        op.f("ix_image_processing_state_inference_status"),
        table_name="image_processing_state",
    )
    op.drop_index(
        op.f("ix_image_processing_state_inference_workflow_id"),
        table_name="image_processing_state",
    )
    op.drop_column("image_processing_state", "inference_completed_at")
    op.drop_column("image_processing_state", "inference_started_at")
    op.drop_column("image_processing_state", "inference_workflow_id")
    op.drop_column("image_processing_state", "inference_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "image_processing_state",
        sa.Column(
            "inference_status",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
            comment="started|image_downloaded|pipeline_loaded|running_models|completed|failed",
        ),
    )
    op.add_column(
        "image_processing_state",
        sa.Column(
            "inference_workflow_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="DBOS workflow UUID for inference workflow (ML model execution)",
        ),
    )
    op.add_column(
        "image_processing_state",
        sa.Column(
            "inference_started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
            comment="When inference workflow started",
        ),
    )
    op.add_column(
        "image_processing_state",
        sa.Column(
            "inference_completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
            comment="When inference workflow completed",
        ),
    )
    op.create_index(
        op.f("ix_image_processing_state_inference_workflow_id"),
        "image_processing_state",
        ["inference_workflow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_image_processing_state_inference_status"),
        "image_processing_state",
        ["inference_status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_processing_state_inference_workflow"),
        "image_processing_state",
        ["inference_workflow_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_processing_state_inference_status"),
        "image_processing_state",
        ["inference_status"],
        unique=False,
    )
    # ### end Alembic commands ###
