"""add_inference_workflow_columns_to_image_processing_state

Revision ID: a4a99b3347b4
Revises: f6280e2e09c1
Create Date: 2025-10-29 13:05:54.086450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4a99b3347b4"
down_revision: Union[str, Sequence[str], None] = "f6280e2e09c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "image_processing_state",
        sa.Column(
            "inference_workflow_id",
            sa.String(length=255),
            nullable=True,
            comment="DBOS workflow UUID for inference workflow (ML model execution)",
        ),
    )
    op.add_column(
        "image_processing_state",
        sa.Column(
            "inference_status",
            sa.String(length=50),
            nullable=True,
            comment="started|image_downloaded|pipeline_loaded|running_models|completed|failed",
        ),
    )
    op.add_column(
        "image_processing_state",
        sa.Column(
            "inference_started_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When inference workflow started",
        ),
    )
    op.add_column(
        "image_processing_state",
        sa.Column(
            "inference_completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When inference workflow completed",
        ),
    )
    op.alter_column(
        "image_processing_state",
        "workflow_id",
        existing_type=sa.VARCHAR(length=255),
        comment="DBOS workflow UUID for image processing workflow (upload/scan/sanitize)",
        existing_comment="DBOS workflow UUID for tracking and recovery",
        existing_nullable=True,
    )
    op.create_index(
        "idx_processing_state_inference_status",
        "image_processing_state",
        ["inference_status"],
        unique=False,
    )
    op.create_index(
        "idx_processing_state_inference_workflow",
        "image_processing_state",
        ["inference_workflow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_image_processing_state_inference_status"),
        "image_processing_state",
        ["inference_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_image_processing_state_inference_workflow_id"),
        "image_processing_state",
        ["inference_workflow_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_image_processing_state_inference_workflow_id"),
        table_name="image_processing_state",
    )
    op.drop_index(
        op.f("ix_image_processing_state_inference_status"),
        table_name="image_processing_state",
    )
    op.drop_index(
        "idx_processing_state_inference_workflow", table_name="image_processing_state"
    )
    op.drop_index(
        "idx_processing_state_inference_status", table_name="image_processing_state"
    )
    op.alter_column(
        "image_processing_state",
        "workflow_id",
        existing_type=sa.VARCHAR(length=255),
        comment="DBOS workflow UUID for tracking and recovery",
        existing_comment="DBOS workflow UUID for image processing workflow (upload/scan/sanitize)",
        existing_nullable=True,
    )
    op.drop_column("image_processing_state", "inference_completed_at")
    op.drop_column("image_processing_state", "inference_started_at")
    op.drop_column("image_processing_state", "inference_status")
    op.drop_column("image_processing_state", "inference_workflow_id")
    # ### end Alembic commands ###
