"""Add unique constraint to rbac_resource name and make it non-nullable

Revision ID: 99edebb303d3
Revises: e8057005353f
Create Date: 2025-10-09 13:52:10.733080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99edebb303d3"
down_revision: Union[str, Sequence[str], None] = "e8057005353f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rbac_resource", "name", existing_type=sa.TEXT(), nullable=False)
    op.create_unique_constraint("uq_rbac_resource_name", "rbac_resource", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_rbac_resource_name", "rbac_resource", type_="unique")
    op.alter_column("rbac_resource", "name", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
