"""Remove semver table and semver_id from change_log

Revision ID: e8057005353f
Revises: e004a8a3305b
Create Date: 2025-10-09 01:58:06.276879

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8057005353f"
down_revision: Union[str, Sequence[str], None] = "e004a8a3305b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("change_log_semver_id_fkey"), "change_log", type_="foreignkey"
    )
    op.drop_column("change_log", "semver_id")
    op.drop_table("semver")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "semver",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("semver", sa.Text(), nullable=False),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("semver_pkey")),
    )
    op.add_column(
        "change_log",
        sa.Column("semver_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("change_log_semver_id_fkey"), "change_log", "semver", ["semver_id"], ["id"]
    )
    # ### end Alembic commands ###
