"""Add unique constraint to rbac_role organization_id and name

Revision ID: e004a8a3305b
Revises: e47e20232a02
Create Date: 2025-10-09 01:40:35.623506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e004a8a3305b'
down_revision: Union[str, Sequence[str], None] = 'e47e20232a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_rbac_role_org_name', 'rbac_role', ['organization_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_rbac_role_org_name', 'rbac_role', type_='unique')
    # ### end Alembic commands ###
