"""Add image_processing_state table for tracking

Revision ID: 0c193341695c
Revises: 7161212e993a
Create Date: 2025-10-20 01:30:14.191851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c193341695c'
down_revision: Union[str, Sequence[str], None] = '7161212e993a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_processing_state',
    sa.Column('picture_id', sa.UUID(), nullable=False, comment='Reference to Picture being processed'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='pending|uploaded|defender_scanning|defender_scanned|sanitizing|sanitized|completed|failed|cancelled'),
    sa.Column('workflow_id', sa.String(length=255), nullable=True, comment='DBOS workflow UUID for tracking and recovery'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('defender_scan_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('defender_scan_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sanitization_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sanitization_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('defender_scan_result', sa.JSON(), nullable=True, comment='Defender scan tags and metadata'),
    sa.Column('malware_detected', sa.Boolean(), nullable=False, comment='True if malware detected by Defender'),
    sa.Column('blob_url_original', sa.String(length=500), nullable=True),
    sa.Column('blob_url_sanitized', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True, comment='Detailed error information including stack traces'),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=False, comment='0-100 progress indicator'),
    sa.ForeignKeyConstraint(['picture_id'], ['picture.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('picture_id')
    )
    op.create_index('idx_processing_state_created', 'image_processing_state', ['created_at'], unique=False)
    op.create_index('idx_processing_state_status', 'image_processing_state', ['status'], unique=False)
    op.create_index('idx_processing_state_workflow', 'image_processing_state', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_image_processing_state_status'), 'image_processing_state', ['status'], unique=False)
    op.create_index(op.f('ix_image_processing_state_workflow_id'), 'image_processing_state', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_processing_state_workflow_id'), table_name='image_processing_state')
    op.drop_index(op.f('ix_image_processing_state_status'), table_name='image_processing_state')
    op.drop_index('idx_processing_state_workflow', table_name='image_processing_state')
    op.drop_index('idx_processing_state_status', table_name='image_processing_state')
    op.drop_index('idx_processing_state_created', table_name='image_processing_state')
    op.drop_table('image_processing_state')
    # ### end Alembic commands ###
