"""Add unique constraint to rbac_permission name and make it non-null

Revision ID: b58746ce2d5d
Revises: 99edebb303d3
Create Date: 2025-10-09 14:13:59.990446

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b58746ce2d5d"
down_revision: Union[str, Sequence[str], None] = "99edebb303d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rbac_permission", "name", existing_type=sa.TEXT(), nullable=False)
    op.create_unique_constraint("uq_rbac_permission_name", "rbac_permission", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_rbac_permission_name", "rbac_permission", type_="unique")
    op.alter_column("rbac_permission", "name", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
