"""add synonym fields to seed table

Revision ID: 030caf3bf366
Revises: 2dc1198f9099
Create Date: 2025-11-26 13:56:36.044021

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "030caf3bf366"
down_revision: Union[str, Sequence[str], None] = "2dc1198f9099"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("seed", sa.Column("synonyms", sa.Text(), nullable=True))
    op.add_column("seed", sa.Column("subspecies_author", sa.Text(), nullable=True))
    op.add_column("seed", sa.Column("variety_author", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seed", "variety_author")
    op.drop_column("seed", "subspecies_author")
    op.drop_column("seed", "synonyms")
    # ### end Alembic commands ###
