"""Device Tables date_created

Revision ID: f6280e2e09c1
Revises: 6cb2139f71bf
Create Date: 2025-10-29 02:37:04.846989

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6280e2e09c1"
down_revision: Union[str, Sequence[str], None] = "6cb2139f71bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first
    op.add_column(
        "device_brand",
        sa.Column("date_created", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "device_lens",
        sa.Column("date_created", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "device_model",
        sa.Column("date_created", sa.DateTime(timezone=True), nullable=True),
    )

    # Populate existing rows with current timestamp
    op.execute(
        """
        UPDATE device_brand
        SET date_created = NOW()
        WHERE date_created IS NULL;
        """
    )
    op.execute(
        """
        UPDATE device_lens
        SET date_created = NOW()
        WHERE date_created IS NULL;
        """
    )
    op.execute(
        """
        UPDATE device_model
        SET date_created = NOW()
        WHERE date_created IS NULL;
        """
    )

    # Now make the columns NOT NULL
    op.alter_column("device_brand", "date_created", nullable=False)
    op.alter_column("device_lens", "date_created", nullable=False)
    op.alter_column("device_model", "date_created", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("device_model", "date_created")
    op.drop_column("device_lens", "date_created")
    op.drop_column("device_brand", "date_created")
    # ### end Alembic commands ###
