PRESETS = {
    "development": {
        "Content-Security-Policy": "default-src 'self';",
        "X-Frame-Options": "DENY",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
        "X-Content-Type-Options": "nosniff",
        "Referrer-Policy": "no-referrer",
        "Permissions-Policy": "accelerometer=(), autoplay=(), camera=(self), clipboard-read=(self), clipboard-write=(self), cross-origin-isolated=(), display-capture=(), encrypted-media=(), fullscreen=(), gamepad=(), geolocation=(), gyroscope=(), hid=(), idle-detection=(), interest-cohort=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), serial=(), sync-xhr=(), unload=(), usb=(), web-share=(), xr-spatial-tracking=()",
        "X-DNS-Prefetch-Control": "off",
        "Expect-CT": "max-age=86400, enforce",
        "Origin-Agent-Cluster": "?1",
        "X-Permitted-Cross-Domain-Policies": "none",
        "Cache-Control": "private, max-age=3600",
    },
    "strict": {
        "Content-Security-Policy": "default-src 'self';",
        # "Content-Security-Policy": "default-src 'self'; script-src 'self' 'unsafe-inline' https://login.microsoftonline.com https://*.microsoftonline.com; style-src 'self' 'unsafe-inline' https://login.microsoftonline.com https://*.microsoftonline.com; img-src 'self' https://login.microsoftonline.com https://*.microsoftonline.com data: blob:; font-src 'self' https://login.microsoftonline.com https://*.microsoftonline.com data:; connect-src 'self' https://login.microsoftonline.com https://*.microsoftonline.com https://graph.microsoft.com; frame-src 'self' https://login.microsoftonline.com https://*.microsoftonline.com; child-src 'self' https://login.microsoftonline.com https://*.microsoftonline.com; form-action 'self' https://login.microsoftonline.com;",
        "X-Frame-Options": "DENY",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
        "X-Content-Type-Options": "nosniff",
        "Referrer-Policy": "no-referrer",
        "Permissions-Policy": "accelerometer=(), autoplay=(), camera=(self), clipboard-read=(self), clipboard-write=(self), cross-origin-isolated=(), display-capture=(), encrypted-media=(), fullscreen=(), gamepad=(), geolocation=(), gyroscope=(), hid=(), idle-detection=(), interest-cohort=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), serial=(), sync-xhr=(), unload=(), usb=(), web-share=(), xr-spatial-tracking=()",
        "X-DNS-Prefetch-Control": "off",
        "Expect-CT": "max-age=86400, enforce",
        "Origin-Agent-Cluster": "?1",
        "Cross-Origin-Embedder-Policy": "require-corp",
        # "Cross-Origin-Embedder-Policy": "credentialless",
        "Cross-Origin-Opener-Policy": "same-origin",
        # "Cross-Origin-Opener-Policy": "same-origin-allow-popups",
        "Cross-Origin-Resource-Policy": "same-origin",
        "X-Permitted-Cross-Domain-Policies": "none",
        "Cache-Control": "private, max-age=3600",
    },
    "relaxed": {
        "Content-Security-Policy": "default-src *;",
        "X-Frame-Options": "SAMEORIGIN",
        "Strict-Transport-Security": "max-age=86400",
        "X-Content-Type-Options": "nosniff",
        "Referrer-Policy": "strict-origin-when-cross-origin",
    },
    "none": {},
}

# clear site data only add to logout         "Clear-Site-Data": "\"cache\",\"cookies\",\"storage\"",
