---
name: Fix Frontend SBOM

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull request number"
        required: true
      node-version:
        description: "Node.js version"
        required: false
        default: "24.5.0"
      npm-version:
        description: "npm version"
        required: false
        default: "11.5.1"

permissions:
  contents: write
  pull-requests: write

jobs:
  fix:
    runs-on: ubuntu-latest

    steps:
      - name: Apply latest patches
        run: |
          sudo apt update && sudo apt upgrade -y

      - name: Fetch PR metadata
        id: prmeta
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = Number("${{ github.event.inputs.pr_number }}");
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            core.setOutput("head_repo", pr.head.repo.full_name);
            core.setOutput("head_ref", pr.head.ref);

      - name: Checkout PR head
        uses: actions/checkout@v6
        with:
          repository: ${{ steps.prmeta.outputs.head_repo }}
          ref: ${{ steps.prmeta.outputs.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ github.event.inputs.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install specific npm version
        run: npm install -g npm@${{ github.event.inputs.npm-version }}

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Generate SBOM
        working-directory: frontend
        run: |
          npx cyclonedx-npm package-lock.json \
            --output-reproducible \
            --package-lock-only \
            -v \
            --sv 1.6 \
            -o sbom.json \
          && printf "\n" >> sbom.json

      - name: Commit & push
        env:
          BRANCH: ${{ steps.prmeta.outputs.head_ref }}
        run: |
          git config user.name "github-actions[bot]"
          git config \
            user.email \
              "41898282+github-actions[bot]@users.noreply.github.com"
          git add frontend/sbom.json

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "chore(sbom): update frontend sbom.json"
          GIT_TERMINAL_PROMPT=0 git push origin "HEAD:refs/heads/${BRANCH}"
