name: Frontend Build and Push

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
      - 'package.json'
      - '.nvmrc'
      - 'tsconfig.json'
    types:
      - opened
      - closed
      - synchronize

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  IS_MONOREPO: true
  FRONTEND_PATH: frontend
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/nachet-frontend

defaults:
  run:
    working-directory: frontend

jobs:
  build-and-push-gcr:
    uses: ./.github/workflows/workflow-build-push-container-github-registry-mono.yml
    #   uses: ai-cfia/github-workflows/.github/workflows/workflow-build-push-container-github-registry-mono.yml@main
    with:
      working-directory: frontend
      container-name: ${{ github.event.repository.name }}-frontend
      tag: ${{ github.sha }}
      registry: ghcr.io/ai-cfia
    secrets: inherit
