name: Terraform Lint
permissions:
  contents: write
  pull-requests: write
  actions: write

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/iac-*.yml"
    types:
      - opened
      - closed
      - synchronize
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/iac-*.yml"

concurrency:
  group: iac-lint-${{ github.ref }}
  cancel-in-progress: true


jobs:
  terraform-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-terraform-check.yml@main
    with:
      config-file-path: '.tflint.hcl'
