name: Repo standards validation & terraform check

permissions:
  contents: read

on:
  pull_request:
    paths:
      - "**"
      - ".github/workflows/repo-std.yml"
    types:
      - opened
      - closed
      - synchronize

jobs:
  repo-standard:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit
  
  terraform-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-terraform-check.yml@main
    with:
      config-file-path: '.tflint.hcl'
