---
name: Secrets Scan Trufflehog
permissions:
  contents: read
  pull-requests: write
  actions: write

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Trufflehog
        uses: trufflesecurity/trufflehog@b140e2b58e65881729b6035ad03a3c0b23d79985
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unknown
